/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CancelReason extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2285900074755451305L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CancelReason\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"comment\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reason\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reasonId\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CancelReason> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CancelReason> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CancelReason> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CancelReason> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CancelReason> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CancelReason to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CancelReason from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CancelReason instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CancelReason fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence comment;
  private java.lang.CharSequence reason;
  private java.lang.CharSequence reasonId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CancelReason() {}

  /**
   * All-args constructor.
   * @param comment The new value for comment
   * @param reason The new value for reason
   * @param reasonId The new value for reasonId
   */
  public CancelReason(java.lang.CharSequence comment, java.lang.CharSequence reason, java.lang.CharSequence reasonId) {
    this.comment = comment;
    this.reason = reason;
    this.reasonId = reasonId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return comment;
    case 1: return reason;
    case 2: return reasonId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: comment = (java.lang.CharSequence)value$; break;
    case 1: reason = (java.lang.CharSequence)value$; break;
    case 2: reasonId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'comment' field.
   * @return The value of the 'comment' field.
   */
  public java.lang.CharSequence getComment() {
    return comment;
  }


  /**
   * Sets the value of the 'comment' field.
   * @param value the value to set.
   */
  public void setComment(java.lang.CharSequence value) {
    this.comment = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'reasonId' field.
   * @return The value of the 'reasonId' field.
   */
  public java.lang.CharSequence getReasonId() {
    return reasonId;
  }


  /**
   * Sets the value of the 'reasonId' field.
   * @param value the value to set.
   */
  public void setReasonId(java.lang.CharSequence value) {
    this.reasonId = value;
  }

  /**
   * Creates a new CancelReason RecordBuilder.
   * @return A new CancelReason RecordBuilder
   */
  public static org.pipeline.trips.avro.CancelReason.Builder newBuilder() {
    return new org.pipeline.trips.avro.CancelReason.Builder();
  }

  /**
   * Creates a new CancelReason RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CancelReason RecordBuilder
   */
  public static org.pipeline.trips.avro.CancelReason.Builder newBuilder(org.pipeline.trips.avro.CancelReason.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.CancelReason.Builder();
    } else {
      return new org.pipeline.trips.avro.CancelReason.Builder(other);
    }
  }

  /**
   * Creates a new CancelReason RecordBuilder by copying an existing CancelReason instance.
   * @param other The existing instance to copy.
   * @return A new CancelReason RecordBuilder
   */
  public static org.pipeline.trips.avro.CancelReason.Builder newBuilder(org.pipeline.trips.avro.CancelReason other) {
    if (other == null) {
      return new org.pipeline.trips.avro.CancelReason.Builder();
    } else {
      return new org.pipeline.trips.avro.CancelReason.Builder(other);
    }
  }

  /**
   * RecordBuilder for CancelReason instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CancelReason>
    implements org.apache.avro.data.RecordBuilder<CancelReason> {

    private java.lang.CharSequence comment;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence reasonId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.CancelReason.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.comment)) {
        this.comment = data().deepCopy(fields()[0].schema(), other.comment);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.reasonId)) {
        this.reasonId = data().deepCopy(fields()[2].schema(), other.reasonId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CancelReason instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.CancelReason other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.comment)) {
        this.comment = data().deepCopy(fields()[0].schema(), other.comment);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reasonId)) {
        this.reasonId = data().deepCopy(fields()[2].schema(), other.reasonId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'comment' field.
      * @return The value.
      */
    public java.lang.CharSequence getComment() {
      return comment;
    }


    /**
      * Sets the value of the 'comment' field.
      * @param value The value of 'comment'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder setComment(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.comment = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'comment' field has been set.
      * @return True if the 'comment' field has been set, false otherwise.
      */
    public boolean hasComment() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'comment' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder clearComment() {
      comment = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reason = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder clearReason() {
      reason = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'reasonId' field.
      * @return The value.
      */
    public java.lang.CharSequence getReasonId() {
      return reasonId;
    }


    /**
      * Sets the value of the 'reasonId' field.
      * @param value The value of 'reasonId'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder setReasonId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.reasonId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'reasonId' field has been set.
      * @return True if the 'reasonId' field has been set, false otherwise.
      */
    public boolean hasReasonId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'reasonId' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.CancelReason.Builder clearReasonId() {
      reasonId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CancelReason build() {
      try {
        CancelReason record = new CancelReason();
        record.comment = fieldSetFlags()[0] ? this.comment : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reason = fieldSetFlags()[1] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.reasonId = fieldSetFlags()[2] ? this.reasonId : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CancelReason>
    WRITER$ = (org.apache.avro.io.DatumWriter<CancelReason>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CancelReason>
    READER$ = (org.apache.avro.io.DatumReader<CancelReason>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.comment == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.comment);
    }

    if (this.reason == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reason);
    }

    if (this.reasonId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reasonId);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.comment = null;
      } else {
        this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.reason = null;
      } else {
        this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.reasonId = null;
      } else {
        this.reasonId = in.readString(this.reasonId instanceof Utf8 ? (Utf8)this.reasonId : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.comment = null;
          } else {
            this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reason = null;
          } else {
            this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reasonId = null;
          } else {
            this.reasonId = in.readString(this.reasonId instanceof Utf8 ? (Utf8)this.reasonId : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










