/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Car extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2219960555783896863L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Car\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"marque\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"immat\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"color\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"energie\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"year\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Car> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Car> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Car> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Car> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Car> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Car to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Car from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Car instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Car fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence model;
  private java.lang.CharSequence marque;
  private java.lang.CharSequence immat;
  private java.lang.CharSequence color;
  private java.lang.CharSequence energie;
  private java.lang.Integer year;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Car() {}

  /**
   * All-args constructor.
   * @param model The new value for model
   * @param marque The new value for marque
   * @param immat The new value for immat
   * @param color The new value for color
   * @param energie The new value for energie
   * @param year The new value for year
   */
  public Car(java.lang.CharSequence model, java.lang.CharSequence marque, java.lang.CharSequence immat, java.lang.CharSequence color, java.lang.CharSequence energie, java.lang.Integer year) {
    this.model = model;
    this.marque = marque;
    this.immat = immat;
    this.color = color;
    this.energie = energie;
    this.year = year;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return model;
    case 1: return marque;
    case 2: return immat;
    case 3: return color;
    case 4: return energie;
    case 5: return year;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: model = (java.lang.CharSequence)value$; break;
    case 1: marque = (java.lang.CharSequence)value$; break;
    case 2: immat = (java.lang.CharSequence)value$; break;
    case 3: color = (java.lang.CharSequence)value$; break;
    case 4: energie = (java.lang.CharSequence)value$; break;
    case 5: year = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'marque' field.
   * @return The value of the 'marque' field.
   */
  public java.lang.CharSequence getMarque() {
    return marque;
  }


  /**
   * Sets the value of the 'marque' field.
   * @param value the value to set.
   */
  public void setMarque(java.lang.CharSequence value) {
    this.marque = value;
  }

  /**
   * Gets the value of the 'immat' field.
   * @return The value of the 'immat' field.
   */
  public java.lang.CharSequence getImmat() {
    return immat;
  }


  /**
   * Sets the value of the 'immat' field.
   * @param value the value to set.
   */
  public void setImmat(java.lang.CharSequence value) {
    this.immat = value;
  }

  /**
   * Gets the value of the 'color' field.
   * @return The value of the 'color' field.
   */
  public java.lang.CharSequence getColor() {
    return color;
  }


  /**
   * Sets the value of the 'color' field.
   * @param value the value to set.
   */
  public void setColor(java.lang.CharSequence value) {
    this.color = value;
  }

  /**
   * Gets the value of the 'energie' field.
   * @return The value of the 'energie' field.
   */
  public java.lang.CharSequence getEnergie() {
    return energie;
  }


  /**
   * Sets the value of the 'energie' field.
   * @param value the value to set.
   */
  public void setEnergie(java.lang.CharSequence value) {
    this.energie = value;
  }

  /**
   * Gets the value of the 'year' field.
   * @return The value of the 'year' field.
   */
  public java.lang.Integer getYear() {
    return year;
  }


  /**
   * Sets the value of the 'year' field.
   * @param value the value to set.
   */
  public void setYear(java.lang.Integer value) {
    this.year = value;
  }

  /**
   * Creates a new Car RecordBuilder.
   * @return A new Car RecordBuilder
   */
  public static org.pipeline.trips.avro.Car.Builder newBuilder() {
    return new org.pipeline.trips.avro.Car.Builder();
  }

  /**
   * Creates a new Car RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Car RecordBuilder
   */
  public static org.pipeline.trips.avro.Car.Builder newBuilder(org.pipeline.trips.avro.Car.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.Car.Builder();
    } else {
      return new org.pipeline.trips.avro.Car.Builder(other);
    }
  }

  /**
   * Creates a new Car RecordBuilder by copying an existing Car instance.
   * @param other The existing instance to copy.
   * @return A new Car RecordBuilder
   */
  public static org.pipeline.trips.avro.Car.Builder newBuilder(org.pipeline.trips.avro.Car other) {
    if (other == null) {
      return new org.pipeline.trips.avro.Car.Builder();
    } else {
      return new org.pipeline.trips.avro.Car.Builder(other);
    }
  }

  /**
   * RecordBuilder for Car instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Car>
    implements org.apache.avro.data.RecordBuilder<Car> {

    private java.lang.CharSequence model;
    private java.lang.CharSequence marque;
    private java.lang.CharSequence immat;
    private java.lang.CharSequence color;
    private java.lang.CharSequence energie;
    private java.lang.Integer year;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.Car.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.model)) {
        this.model = data().deepCopy(fields()[0].schema(), other.model);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.marque)) {
        this.marque = data().deepCopy(fields()[1].schema(), other.marque);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.immat)) {
        this.immat = data().deepCopy(fields()[2].schema(), other.immat);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.color)) {
        this.color = data().deepCopy(fields()[3].schema(), other.color);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.energie)) {
        this.energie = data().deepCopy(fields()[4].schema(), other.energie);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.year)) {
        this.year = data().deepCopy(fields()[5].schema(), other.year);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Car instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.Car other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.model)) {
        this.model = data().deepCopy(fields()[0].schema(), other.model);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.marque)) {
        this.marque = data().deepCopy(fields()[1].schema(), other.marque);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.immat)) {
        this.immat = data().deepCopy(fields()[2].schema(), other.immat);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.color)) {
        this.color = data().deepCopy(fields()[3].schema(), other.color);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.energie)) {
        this.energie = data().deepCopy(fields()[4].schema(), other.energie);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.year)) {
        this.year = data().deepCopy(fields()[5].schema(), other.year);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.model = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearModel() {
      model = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'marque' field.
      * @return The value.
      */
    public java.lang.CharSequence getMarque() {
      return marque;
    }


    /**
      * Sets the value of the 'marque' field.
      * @param value The value of 'marque'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setMarque(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.marque = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'marque' field has been set.
      * @return True if the 'marque' field has been set, false otherwise.
      */
    public boolean hasMarque() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'marque' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearMarque() {
      marque = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'immat' field.
      * @return The value.
      */
    public java.lang.CharSequence getImmat() {
      return immat;
    }


    /**
      * Sets the value of the 'immat' field.
      * @param value The value of 'immat'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setImmat(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.immat = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'immat' field has been set.
      * @return True if the 'immat' field has been set, false otherwise.
      */
    public boolean hasImmat() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'immat' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearImmat() {
      immat = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'color' field.
      * @return The value.
      */
    public java.lang.CharSequence getColor() {
      return color;
    }


    /**
      * Sets the value of the 'color' field.
      * @param value The value of 'color'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setColor(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.color = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'color' field has been set.
      * @return True if the 'color' field has been set, false otherwise.
      */
    public boolean hasColor() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'color' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearColor() {
      color = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'energie' field.
      * @return The value.
      */
    public java.lang.CharSequence getEnergie() {
      return energie;
    }


    /**
      * Sets the value of the 'energie' field.
      * @param value The value of 'energie'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setEnergie(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.energie = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'energie' field has been set.
      * @return True if the 'energie' field has been set, false otherwise.
      */
    public boolean hasEnergie() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'energie' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearEnergie() {
      energie = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'year' field.
      * @return The value.
      */
    public java.lang.Integer getYear() {
      return year;
    }


    /**
      * Sets the value of the 'year' field.
      * @param value The value of 'year'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder setYear(java.lang.Integer value) {
      validate(fields()[5], value);
      this.year = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'year' field has been set.
      * @return True if the 'year' field has been set, false otherwise.
      */
    public boolean hasYear() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'year' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.Car.Builder clearYear() {
      year = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Car build() {
      try {
        Car record = new Car();
        record.model = fieldSetFlags()[0] ? this.model : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.marque = fieldSetFlags()[1] ? this.marque : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.immat = fieldSetFlags()[2] ? this.immat : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.color = fieldSetFlags()[3] ? this.color : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.energie = fieldSetFlags()[4] ? this.energie : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.year = fieldSetFlags()[5] ? this.year : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Car>
    WRITER$ = (org.apache.avro.io.DatumWriter<Car>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Car>
    READER$ = (org.apache.avro.io.DatumReader<Car>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.model == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.model);
    }

    if (this.marque == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.marque);
    }

    if (this.immat == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.immat);
    }

    if (this.color == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.color);
    }

    if (this.energie == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.energie);
    }

    if (this.year == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.year);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.model = null;
      } else {
        this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.marque = null;
      } else {
        this.marque = in.readString(this.marque instanceof Utf8 ? (Utf8)this.marque : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.immat = null;
      } else {
        this.immat = in.readString(this.immat instanceof Utf8 ? (Utf8)this.immat : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.color = null;
      } else {
        this.color = in.readString(this.color instanceof Utf8 ? (Utf8)this.color : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.energie = null;
      } else {
        this.energie = in.readString(this.energie instanceof Utf8 ? (Utf8)this.energie : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.year = null;
      } else {
        this.year = in.readInt();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.model = null;
          } else {
            this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.marque = null;
          } else {
            this.marque = in.readString(this.marque instanceof Utf8 ? (Utf8)this.marque : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.immat = null;
          } else {
            this.immat = in.readString(this.immat instanceof Utf8 ? (Utf8)this.immat : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.color = null;
          } else {
            this.color = in.readString(this.color instanceof Utf8 ? (Utf8)this.color : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.energie = null;
          } else {
            this.energie = in.readString(this.energie instanceof Utf8 ? (Utf8)this.energie : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.year = null;
          } else {
            this.year = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










