/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceProfile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -104552467696652762L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceProfile\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"active\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"app_lang\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"app_version\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"device_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"device_lang\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fcm_token\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"last_used\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"location\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DeviceLocation\",\"fields\":[{\"name\":\"coordinates\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null}]}],\"default\":null},{\"name\":\"model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"os_version\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"platform\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"retired_at\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ya_device_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DeviceProfile> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceProfile> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceProfile> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceProfile> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceProfile> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceProfile to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceProfile from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceProfile instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceProfile fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Boolean active;
  private java.lang.CharSequence app_lang;
  private java.lang.CharSequence app_version;
  private java.lang.CharSequence brand;
  private java.time.Instant created_at;
  private java.lang.CharSequence device_id;
  private java.lang.CharSequence device_lang;
  private java.lang.CharSequence fcm_token;
  private java.time.Instant last_used;
  private org.pipeline.trips.avro.DeviceLocation location;
  private java.lang.CharSequence model;
  private java.lang.CharSequence os_version;
  private java.lang.CharSequence platform;
  private java.lang.CharSequence retired_at;
  private java.lang.CharSequence ya_device_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceProfile() {}

  /**
   * All-args constructor.
   * @param active The new value for active
   * @param app_lang The new value for app_lang
   * @param app_version The new value for app_version
   * @param brand The new value for brand
   * @param created_at The new value for created_at
   * @param device_id The new value for device_id
   * @param device_lang The new value for device_lang
   * @param fcm_token The new value for fcm_token
   * @param last_used The new value for last_used
   * @param location The new value for location
   * @param model The new value for model
   * @param os_version The new value for os_version
   * @param platform The new value for platform
   * @param retired_at The new value for retired_at
   * @param ya_device_id The new value for ya_device_id
   */
  public DeviceProfile(java.lang.Boolean active, java.lang.CharSequence app_lang, java.lang.CharSequence app_version, java.lang.CharSequence brand, java.time.Instant created_at, java.lang.CharSequence device_id, java.lang.CharSequence device_lang, java.lang.CharSequence fcm_token, java.time.Instant last_used, org.pipeline.trips.avro.DeviceLocation location, java.lang.CharSequence model, java.lang.CharSequence os_version, java.lang.CharSequence platform, java.lang.CharSequence retired_at, java.lang.CharSequence ya_device_id) {
    this.active = active;
    this.app_lang = app_lang;
    this.app_version = app_version;
    this.brand = brand;
    this.created_at = created_at;
    this.device_id = device_id;
    this.device_lang = device_lang;
    this.fcm_token = fcm_token;
    this.last_used = last_used;
    this.location = location;
    this.model = model;
    this.os_version = os_version;
    this.platform = platform;
    this.retired_at = retired_at;
    this.ya_device_id = ya_device_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return active;
    case 1: return app_lang;
    case 2: return app_version;
    case 3: return brand;
    case 4: return created_at;
    case 5: return device_id;
    case 6: return device_lang;
    case 7: return fcm_token;
    case 8: return last_used;
    case 9: return location;
    case 10: return model;
    case 11: return os_version;
    case 12: return platform;
    case 13: return retired_at;
    case 14: return ya_device_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: active = (java.lang.Boolean)value$; break;
    case 1: app_lang = (java.lang.CharSequence)value$; break;
    case 2: app_version = (java.lang.CharSequence)value$; break;
    case 3: brand = (java.lang.CharSequence)value$; break;
    case 4: created_at = (java.time.Instant)value$; break;
    case 5: device_id = (java.lang.CharSequence)value$; break;
    case 6: device_lang = (java.lang.CharSequence)value$; break;
    case 7: fcm_token = (java.lang.CharSequence)value$; break;
    case 8: last_used = (java.time.Instant)value$; break;
    case 9: location = (org.pipeline.trips.avro.DeviceLocation)value$; break;
    case 10: model = (java.lang.CharSequence)value$; break;
    case 11: os_version = (java.lang.CharSequence)value$; break;
    case 12: platform = (java.lang.CharSequence)value$; break;
    case 13: retired_at = (java.lang.CharSequence)value$; break;
    case 14: ya_device_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public java.lang.Boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(java.lang.Boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'app_lang' field.
   * @return The value of the 'app_lang' field.
   */
  public java.lang.CharSequence getAppLang() {
    return app_lang;
  }


  /**
   * Sets the value of the 'app_lang' field.
   * @param value the value to set.
   */
  public void setAppLang(java.lang.CharSequence value) {
    this.app_lang = value;
  }

  /**
   * Gets the value of the 'app_version' field.
   * @return The value of the 'app_version' field.
   */
  public java.lang.CharSequence getAppVersion() {
    return app_version;
  }


  /**
   * Sets the value of the 'app_version' field.
   * @param value the value to set.
   */
  public void setAppVersion(java.lang.CharSequence value) {
    this.app_version = value;
  }

  /**
   * Gets the value of the 'brand' field.
   * @return The value of the 'brand' field.
   */
  public java.lang.CharSequence getBrand() {
    return brand;
  }


  /**
   * Sets the value of the 'brand' field.
   * @param value the value to set.
   */
  public void setBrand(java.lang.CharSequence value) {
    this.brand = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.time.Instant getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'device_id' field.
   * @return The value of the 'device_id' field.
   */
  public java.lang.CharSequence getDeviceId() {
    return device_id;
  }


  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.CharSequence value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'device_lang' field.
   * @return The value of the 'device_lang' field.
   */
  public java.lang.CharSequence getDeviceLang() {
    return device_lang;
  }


  /**
   * Sets the value of the 'device_lang' field.
   * @param value the value to set.
   */
  public void setDeviceLang(java.lang.CharSequence value) {
    this.device_lang = value;
  }

  /**
   * Gets the value of the 'fcm_token' field.
   * @return The value of the 'fcm_token' field.
   */
  public java.lang.CharSequence getFcmToken() {
    return fcm_token;
  }


  /**
   * Sets the value of the 'fcm_token' field.
   * @param value the value to set.
   */
  public void setFcmToken(java.lang.CharSequence value) {
    this.fcm_token = value;
  }

  /**
   * Gets the value of the 'last_used' field.
   * @return The value of the 'last_used' field.
   */
  public java.time.Instant getLastUsed() {
    return last_used;
  }


  /**
   * Sets the value of the 'last_used' field.
   * @param value the value to set.
   */
  public void setLastUsed(java.time.Instant value) {
    this.last_used = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public org.pipeline.trips.avro.DeviceLocation getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(org.pipeline.trips.avro.DeviceLocation value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'os_version' field.
   * @return The value of the 'os_version' field.
   */
  public java.lang.CharSequence getOsVersion() {
    return os_version;
  }


  /**
   * Sets the value of the 'os_version' field.
   * @param value the value to set.
   */
  public void setOsVersion(java.lang.CharSequence value) {
    this.os_version = value;
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.CharSequence getPlatform() {
    return platform;
  }


  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.CharSequence value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'retired_at' field.
   * @return The value of the 'retired_at' field.
   */
  public java.lang.CharSequence getRetiredAt() {
    return retired_at;
  }


  /**
   * Sets the value of the 'retired_at' field.
   * @param value the value to set.
   */
  public void setRetiredAt(java.lang.CharSequence value) {
    this.retired_at = value;
  }

  /**
   * Gets the value of the 'ya_device_id' field.
   * @return The value of the 'ya_device_id' field.
   */
  public java.lang.CharSequence getYaDeviceId() {
    return ya_device_id;
  }


  /**
   * Sets the value of the 'ya_device_id' field.
   * @param value the value to set.
   */
  public void setYaDeviceId(java.lang.CharSequence value) {
    this.ya_device_id = value;
  }

  /**
   * Creates a new DeviceProfile RecordBuilder.
   * @return A new DeviceProfile RecordBuilder
   */
  public static org.pipeline.trips.avro.DeviceProfile.Builder newBuilder() {
    return new org.pipeline.trips.avro.DeviceProfile.Builder();
  }

  /**
   * Creates a new DeviceProfile RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceProfile RecordBuilder
   */
  public static org.pipeline.trips.avro.DeviceProfile.Builder newBuilder(org.pipeline.trips.avro.DeviceProfile.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.DeviceProfile.Builder();
    } else {
      return new org.pipeline.trips.avro.DeviceProfile.Builder(other);
    }
  }

  /**
   * Creates a new DeviceProfile RecordBuilder by copying an existing DeviceProfile instance.
   * @param other The existing instance to copy.
   * @return A new DeviceProfile RecordBuilder
   */
  public static org.pipeline.trips.avro.DeviceProfile.Builder newBuilder(org.pipeline.trips.avro.DeviceProfile other) {
    if (other == null) {
      return new org.pipeline.trips.avro.DeviceProfile.Builder();
    } else {
      return new org.pipeline.trips.avro.DeviceProfile.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceProfile instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceProfile>
    implements org.apache.avro.data.RecordBuilder<DeviceProfile> {

    private java.lang.Boolean active;
    private java.lang.CharSequence app_lang;
    private java.lang.CharSequence app_version;
    private java.lang.CharSequence brand;
    private java.time.Instant created_at;
    private java.lang.CharSequence device_id;
    private java.lang.CharSequence device_lang;
    private java.lang.CharSequence fcm_token;
    private java.time.Instant last_used;
    private org.pipeline.trips.avro.DeviceLocation location;
    private org.pipeline.trips.avro.DeviceLocation.Builder locationBuilder;
    private java.lang.CharSequence model;
    private java.lang.CharSequence os_version;
    private java.lang.CharSequence platform;
    private java.lang.CharSequence retired_at;
    private java.lang.CharSequence ya_device_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.DeviceProfile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.app_lang)) {
        this.app_lang = data().deepCopy(fields()[1].schema(), other.app_lang);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.app_version)) {
        this.app_version = data().deepCopy(fields()[2].schema(), other.app_version);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.device_id)) {
        this.device_id = data().deepCopy(fields()[5].schema(), other.device_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.device_lang)) {
        this.device_lang = data().deepCopy(fields()[6].schema(), other.device_lang);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.fcm_token)) {
        this.fcm_token = data().deepCopy(fields()[7].schema(), other.fcm_token);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.last_used)) {
        this.last_used = data().deepCopy(fields()[8].schema(), other.last_used);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = org.pipeline.trips.avro.DeviceLocation.newBuilder(other.getLocationBuilder());
      }
      if (isValidValue(fields()[10], other.model)) {
        this.model = data().deepCopy(fields()[10].schema(), other.model);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.os_version)) {
        this.os_version = data().deepCopy(fields()[11].schema(), other.os_version);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.platform)) {
        this.platform = data().deepCopy(fields()[12].schema(), other.platform);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.retired_at)) {
        this.retired_at = data().deepCopy(fields()[13].schema(), other.retired_at);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.ya_device_id)) {
        this.ya_device_id = data().deepCopy(fields()[14].schema(), other.ya_device_id);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceProfile instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.DeviceProfile other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.app_lang)) {
        this.app_lang = data().deepCopy(fields()[1].schema(), other.app_lang);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.app_version)) {
        this.app_version = data().deepCopy(fields()[2].schema(), other.app_version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.device_id)) {
        this.device_id = data().deepCopy(fields()[5].schema(), other.device_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.device_lang)) {
        this.device_lang = data().deepCopy(fields()[6].schema(), other.device_lang);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.fcm_token)) {
        this.fcm_token = data().deepCopy(fields()[7].schema(), other.fcm_token);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.last_used)) {
        this.last_used = data().deepCopy(fields()[8].schema(), other.last_used);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = true;
      }
      this.locationBuilder = null;
      if (isValidValue(fields()[10], other.model)) {
        this.model = data().deepCopy(fields()[10].schema(), other.model);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.os_version)) {
        this.os_version = data().deepCopy(fields()[11].schema(), other.os_version);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.platform)) {
        this.platform = data().deepCopy(fields()[12].schema(), other.platform);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.retired_at)) {
        this.retired_at = data().deepCopy(fields()[13].schema(), other.retired_at);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.ya_device_id)) {
        this.ya_device_id = data().deepCopy(fields()[14].schema(), other.ya_device_id);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public java.lang.Boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setActive(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.active = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearActive() {
      active = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'app_lang' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppLang() {
      return app_lang;
    }


    /**
      * Sets the value of the 'app_lang' field.
      * @param value The value of 'app_lang'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setAppLang(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.app_lang = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'app_lang' field has been set.
      * @return True if the 'app_lang' field has been set, false otherwise.
      */
    public boolean hasAppLang() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'app_lang' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearAppLang() {
      app_lang = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'app_version' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppVersion() {
      return app_version;
    }


    /**
      * Sets the value of the 'app_version' field.
      * @param value The value of 'app_version'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setAppVersion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.app_version = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'app_version' field has been set.
      * @return True if the 'app_version' field has been set, false otherwise.
      */
    public boolean hasAppVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'app_version' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearAppVersion() {
      app_version = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'brand' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrand() {
      return brand;
    }


    /**
      * Sets the value of the 'brand' field.
      * @param value The value of 'brand'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setBrand(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.brand = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'brand' field has been set.
      * @return True if the 'brand' field has been set, false otherwise.
      */
    public boolean hasBrand() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'brand' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearBrand() {
      brand = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.created_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceId() {
      return device_id;
    }


    /**
      * Sets the value of the 'device_id' field.
      * @param value The value of 'device_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setDeviceId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.device_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'device_id' field has been set.
      * @return True if the 'device_id' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'device_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_lang' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceLang() {
      return device_lang;
    }


    /**
      * Sets the value of the 'device_lang' field.
      * @param value The value of 'device_lang'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setDeviceLang(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.device_lang = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'device_lang' field has been set.
      * @return True if the 'device_lang' field has been set, false otherwise.
      */
    public boolean hasDeviceLang() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'device_lang' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearDeviceLang() {
      device_lang = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'fcm_token' field.
      * @return The value.
      */
    public java.lang.CharSequence getFcmToken() {
      return fcm_token;
    }


    /**
      * Sets the value of the 'fcm_token' field.
      * @param value The value of 'fcm_token'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setFcmToken(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.fcm_token = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'fcm_token' field has been set.
      * @return True if the 'fcm_token' field has been set, false otherwise.
      */
    public boolean hasFcmToken() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'fcm_token' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearFcmToken() {
      fcm_token = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_used' field.
      * @return The value.
      */
    public java.time.Instant getLastUsed() {
      return last_used;
    }


    /**
      * Sets the value of the 'last_used' field.
      * @param value The value of 'last_used'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setLastUsed(java.time.Instant value) {
      validate(fields()[8], value);
      this.last_used = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'last_used' field has been set.
      * @return True if the 'last_used' field has been set, false otherwise.
      */
    public boolean hasLastUsed() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'last_used' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearLastUsed() {
      last_used = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.DeviceLocation getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setLocation(org.pipeline.trips.avro.DeviceLocation value) {
      validate(fields()[9], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.DeviceLocation.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(org.pipeline.trips.avro.DeviceLocation.newBuilder(location));
        } else {
          setLocationBuilder(org.pipeline.trips.avro.DeviceLocation.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.DeviceProfile.Builder setLocationBuilder(org.pipeline.trips.avro.DeviceLocation.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.model = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearModel() {
      model = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'os_version' field.
      * @return The value.
      */
    public java.lang.CharSequence getOsVersion() {
      return os_version;
    }


    /**
      * Sets the value of the 'os_version' field.
      * @param value The value of 'os_version'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setOsVersion(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.os_version = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'os_version' field has been set.
      * @return True if the 'os_version' field has been set, false otherwise.
      */
    public boolean hasOsVersion() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'os_version' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearOsVersion() {
      os_version = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.CharSequence getPlatform() {
      return platform;
    }


    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setPlatform(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.platform = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'retired_at' field.
      * @return The value.
      */
    public java.lang.CharSequence getRetiredAt() {
      return retired_at;
    }


    /**
      * Sets the value of the 'retired_at' field.
      * @param value The value of 'retired_at'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setRetiredAt(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.retired_at = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'retired_at' field has been set.
      * @return True if the 'retired_at' field has been set, false otherwise.
      */
    public boolean hasRetiredAt() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'retired_at' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearRetiredAt() {
      retired_at = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'ya_device_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getYaDeviceId() {
      return ya_device_id;
    }


    /**
      * Sets the value of the 'ya_device_id' field.
      * @param value The value of 'ya_device_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder setYaDeviceId(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.ya_device_id = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'ya_device_id' field has been set.
      * @return True if the 'ya_device_id' field has been set, false otherwise.
      */
    public boolean hasYaDeviceId() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'ya_device_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DeviceProfile.Builder clearYaDeviceId() {
      ya_device_id = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceProfile build() {
      try {
        DeviceProfile record = new DeviceProfile();
        record.active = fieldSetFlags()[0] ? this.active : (java.lang.Boolean) defaultValue(fields()[0]);
        record.app_lang = fieldSetFlags()[1] ? this.app_lang : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.app_version = fieldSetFlags()[2] ? this.app_version : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.brand = fieldSetFlags()[3] ? this.brand : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.created_at = fieldSetFlags()[4] ? this.created_at : (java.time.Instant) defaultValue(fields()[4]);
        record.device_id = fieldSetFlags()[5] ? this.device_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.device_lang = fieldSetFlags()[6] ? this.device_lang : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.fcm_token = fieldSetFlags()[7] ? this.fcm_token : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.last_used = fieldSetFlags()[8] ? this.last_used : (java.time.Instant) defaultValue(fields()[8]);
        if (locationBuilder != null) {
          try {
            record.location = this.locationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("location"));
            throw e;
          }
        } else {
          record.location = fieldSetFlags()[9] ? this.location : (org.pipeline.trips.avro.DeviceLocation) defaultValue(fields()[9]);
        }
        record.model = fieldSetFlags()[10] ? this.model : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.os_version = fieldSetFlags()[11] ? this.os_version : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.platform = fieldSetFlags()[12] ? this.platform : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.retired_at = fieldSetFlags()[13] ? this.retired_at : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.ya_device_id = fieldSetFlags()[14] ? this.ya_device_id : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceProfile>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceProfile>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceProfile>
    READER$ = (org.apache.avro.io.DatumReader<DeviceProfile>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










