/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DriverTax extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9147054398164289063L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DriverTax\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"amount\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"label\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Label\",\"fields\":[{\"name\":\"ar\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"en\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fr\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"driver_tax_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DriverTax> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DriverTax> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DriverTax> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DriverTax> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DriverTax> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DriverTax to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DriverTax from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DriverTax instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DriverTax fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Double amount;
  private org.pipeline.trips.avro.Label label;
  private java.lang.CharSequence code;
  private java.lang.CharSequence driver_tax_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DriverTax() {}

  /**
   * All-args constructor.
   * @param amount The new value for amount
   * @param label The new value for label
   * @param code The new value for code
   * @param driver_tax_id The new value for driver_tax_id
   */
  public DriverTax(java.lang.Double amount, org.pipeline.trips.avro.Label label, java.lang.CharSequence code, java.lang.CharSequence driver_tax_id) {
    this.amount = amount;
    this.label = label;
    this.code = code;
    this.driver_tax_id = driver_tax_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return amount;
    case 1: return label;
    case 2: return code;
    case 3: return driver_tax_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: amount = (java.lang.Double)value$; break;
    case 1: label = (org.pipeline.trips.avro.Label)value$; break;
    case 2: code = (java.lang.CharSequence)value$; break;
    case 3: driver_tax_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.Double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.Double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public org.pipeline.trips.avro.Label getLabel() {
    return label;
  }


  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(org.pipeline.trips.avro.Label value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'driver_tax_id' field.
   * @return The value of the 'driver_tax_id' field.
   */
  public java.lang.CharSequence getDriverTaxId() {
    return driver_tax_id;
  }


  /**
   * Sets the value of the 'driver_tax_id' field.
   * @param value the value to set.
   */
  public void setDriverTaxId(java.lang.CharSequence value) {
    this.driver_tax_id = value;
  }

  /**
   * Creates a new DriverTax RecordBuilder.
   * @return A new DriverTax RecordBuilder
   */
  public static org.pipeline.trips.avro.DriverTax.Builder newBuilder() {
    return new org.pipeline.trips.avro.DriverTax.Builder();
  }

  /**
   * Creates a new DriverTax RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DriverTax RecordBuilder
   */
  public static org.pipeline.trips.avro.DriverTax.Builder newBuilder(org.pipeline.trips.avro.DriverTax.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.DriverTax.Builder();
    } else {
      return new org.pipeline.trips.avro.DriverTax.Builder(other);
    }
  }

  /**
   * Creates a new DriverTax RecordBuilder by copying an existing DriverTax instance.
   * @param other The existing instance to copy.
   * @return A new DriverTax RecordBuilder
   */
  public static org.pipeline.trips.avro.DriverTax.Builder newBuilder(org.pipeline.trips.avro.DriverTax other) {
    if (other == null) {
      return new org.pipeline.trips.avro.DriverTax.Builder();
    } else {
      return new org.pipeline.trips.avro.DriverTax.Builder(other);
    }
  }

  /**
   * RecordBuilder for DriverTax instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DriverTax>
    implements org.apache.avro.data.RecordBuilder<DriverTax> {

    private java.lang.Double amount;
    private org.pipeline.trips.avro.Label label;
    private org.pipeline.trips.avro.Label.Builder labelBuilder;
    private java.lang.CharSequence code;
    private java.lang.CharSequence driver_tax_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.DriverTax.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasLabelBuilder()) {
        this.labelBuilder = org.pipeline.trips.avro.Label.newBuilder(other.getLabelBuilder());
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.driver_tax_id)) {
        this.driver_tax_id = data().deepCopy(fields()[3].schema(), other.driver_tax_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DriverTax instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.DriverTax other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.amount)) {
        this.amount = data().deepCopy(fields()[0].schema(), other.amount);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      this.labelBuilder = null;
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.driver_tax_id)) {
        this.driver_tax_id = data().deepCopy(fields()[3].schema(), other.driver_tax_id);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.Double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder setAmount(java.lang.Double value) {
      validate(fields()[0], value);
      this.amount = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.Label getLabel() {
      return label;
    }


    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder setLabel(org.pipeline.trips.avro.Label value) {
      validate(fields()[1], value);
      this.labelBuilder = null;
      this.label = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'label' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.Label.Builder getLabelBuilder() {
      if (labelBuilder == null) {
        if (hasLabel()) {
          setLabelBuilder(org.pipeline.trips.avro.Label.newBuilder(label));
        } else {
          setLabelBuilder(org.pipeline.trips.avro.Label.newBuilder());
        }
      }
      return labelBuilder;
    }

    /**
     * Sets the Builder instance for the 'label' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.DriverTax.Builder setLabelBuilder(org.pipeline.trips.avro.Label.Builder value) {
      clearLabel();
      labelBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'label' field has an active Builder instance
     * @return True if the 'label' field has an active Builder instance
     */
    public boolean hasLabelBuilder() {
      return labelBuilder != null;
    }

    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder clearLabel() {
      label = null;
      labelBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder clearCode() {
      code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'driver_tax_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getDriverTaxId() {
      return driver_tax_id;
    }


    /**
      * Sets the value of the 'driver_tax_id' field.
      * @param value The value of 'driver_tax_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder setDriverTaxId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.driver_tax_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'driver_tax_id' field has been set.
      * @return True if the 'driver_tax_id' field has been set, false otherwise.
      */
    public boolean hasDriverTaxId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'driver_tax_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.DriverTax.Builder clearDriverTaxId() {
      driver_tax_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DriverTax build() {
      try {
        DriverTax record = new DriverTax();
        record.amount = fieldSetFlags()[0] ? this.amount : (java.lang.Double) defaultValue(fields()[0]);
        if (labelBuilder != null) {
          try {
            record.label = this.labelBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("label"));
            throw e;
          }
        } else {
          record.label = fieldSetFlags()[1] ? this.label : (org.pipeline.trips.avro.Label) defaultValue(fields()[1]);
        }
        record.code = fieldSetFlags()[2] ? this.code : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.driver_tax_id = fieldSetFlags()[3] ? this.driver_tax_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DriverTax>
    WRITER$ = (org.apache.avro.io.DatumWriter<DriverTax>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DriverTax>
    READER$ = (org.apache.avro.io.DatumReader<DriverTax>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.amount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.amount);
    }

    if (this.label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.label.customEncode(out);
    }

    if (this.code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.code);
    }

    if (this.driver_tax_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.driver_tax_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.amount = null;
      } else {
        this.amount = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.label = null;
      } else {
        if (this.label == null) {
          this.label = new org.pipeline.trips.avro.Label();
        }
        this.label.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.code = null;
      } else {
        this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.driver_tax_id = null;
      } else {
        this.driver_tax_id = in.readString(this.driver_tax_id instanceof Utf8 ? (Utf8)this.driver_tax_id : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.amount = null;
          } else {
            this.amount = in.readDouble();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.label = null;
          } else {
            if (this.label == null) {
              this.label = new org.pipeline.trips.avro.Label();
            }
            this.label.customDecode(in);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.code = null;
          } else {
            this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.driver_tax_id = null;
          } else {
            this.driver_tax_id = in.readString(this.driver_tax_id instanceof Utf8 ? (Utf8)this.driver_tax_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










