/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GroupPermissions extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -426019796646913913L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GroupPermissions\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"byPassBalance\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"autoApproval\",\"type\":[\"null\",\"boolean\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GroupPermissions> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GroupPermissions> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GroupPermissions> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GroupPermissions> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GroupPermissions> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GroupPermissions to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GroupPermissions from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GroupPermissions instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GroupPermissions fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Boolean byPassBalance;
  private java.lang.Boolean autoApproval;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GroupPermissions() {}

  /**
   * All-args constructor.
   * @param byPassBalance The new value for byPassBalance
   * @param autoApproval The new value for autoApproval
   */
  public GroupPermissions(java.lang.Boolean byPassBalance, java.lang.Boolean autoApproval) {
    this.byPassBalance = byPassBalance;
    this.autoApproval = autoApproval;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return byPassBalance;
    case 1: return autoApproval;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: byPassBalance = (java.lang.Boolean)value$; break;
    case 1: autoApproval = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'byPassBalance' field.
   * @return The value of the 'byPassBalance' field.
   */
  public java.lang.Boolean getByPassBalance() {
    return byPassBalance;
  }


  /**
   * Sets the value of the 'byPassBalance' field.
   * @param value the value to set.
   */
  public void setByPassBalance(java.lang.Boolean value) {
    this.byPassBalance = value;
  }

  /**
   * Gets the value of the 'autoApproval' field.
   * @return The value of the 'autoApproval' field.
   */
  public java.lang.Boolean getAutoApproval() {
    return autoApproval;
  }


  /**
   * Sets the value of the 'autoApproval' field.
   * @param value the value to set.
   */
  public void setAutoApproval(java.lang.Boolean value) {
    this.autoApproval = value;
  }

  /**
   * Creates a new GroupPermissions RecordBuilder.
   * @return A new GroupPermissions RecordBuilder
   */
  public static org.pipeline.trips.avro.GroupPermissions.Builder newBuilder() {
    return new org.pipeline.trips.avro.GroupPermissions.Builder();
  }

  /**
   * Creates a new GroupPermissions RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GroupPermissions RecordBuilder
   */
  public static org.pipeline.trips.avro.GroupPermissions.Builder newBuilder(org.pipeline.trips.avro.GroupPermissions.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.GroupPermissions.Builder();
    } else {
      return new org.pipeline.trips.avro.GroupPermissions.Builder(other);
    }
  }

  /**
   * Creates a new GroupPermissions RecordBuilder by copying an existing GroupPermissions instance.
   * @param other The existing instance to copy.
   * @return A new GroupPermissions RecordBuilder
   */
  public static org.pipeline.trips.avro.GroupPermissions.Builder newBuilder(org.pipeline.trips.avro.GroupPermissions other) {
    if (other == null) {
      return new org.pipeline.trips.avro.GroupPermissions.Builder();
    } else {
      return new org.pipeline.trips.avro.GroupPermissions.Builder(other);
    }
  }

  /**
   * RecordBuilder for GroupPermissions instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GroupPermissions>
    implements org.apache.avro.data.RecordBuilder<GroupPermissions> {

    private java.lang.Boolean byPassBalance;
    private java.lang.Boolean autoApproval;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.GroupPermissions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.byPassBalance)) {
        this.byPassBalance = data().deepCopy(fields()[0].schema(), other.byPassBalance);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.autoApproval)) {
        this.autoApproval = data().deepCopy(fields()[1].schema(), other.autoApproval);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GroupPermissions instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.GroupPermissions other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.byPassBalance)) {
        this.byPassBalance = data().deepCopy(fields()[0].schema(), other.byPassBalance);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.autoApproval)) {
        this.autoApproval = data().deepCopy(fields()[1].schema(), other.autoApproval);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'byPassBalance' field.
      * @return The value.
      */
    public java.lang.Boolean getByPassBalance() {
      return byPassBalance;
    }


    /**
      * Sets the value of the 'byPassBalance' field.
      * @param value The value of 'byPassBalance'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.GroupPermissions.Builder setByPassBalance(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.byPassBalance = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'byPassBalance' field has been set.
      * @return True if the 'byPassBalance' field has been set, false otherwise.
      */
    public boolean hasByPassBalance() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'byPassBalance' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.GroupPermissions.Builder clearByPassBalance() {
      byPassBalance = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'autoApproval' field.
      * @return The value.
      */
    public java.lang.Boolean getAutoApproval() {
      return autoApproval;
    }


    /**
      * Sets the value of the 'autoApproval' field.
      * @param value The value of 'autoApproval'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.GroupPermissions.Builder setAutoApproval(java.lang.Boolean value) {
      validate(fields()[1], value);
      this.autoApproval = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'autoApproval' field has been set.
      * @return True if the 'autoApproval' field has been set, false otherwise.
      */
    public boolean hasAutoApproval() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'autoApproval' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.GroupPermissions.Builder clearAutoApproval() {
      autoApproval = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GroupPermissions build() {
      try {
        GroupPermissions record = new GroupPermissions();
        record.byPassBalance = fieldSetFlags()[0] ? this.byPassBalance : (java.lang.Boolean) defaultValue(fields()[0]);
        record.autoApproval = fieldSetFlags()[1] ? this.autoApproval : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GroupPermissions>
    WRITER$ = (org.apache.avro.io.DatumWriter<GroupPermissions>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GroupPermissions>
    READER$ = (org.apache.avro.io.DatumReader<GroupPermissions>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.byPassBalance == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.byPassBalance);
    }

    if (this.autoApproval == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.autoApproval);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.byPassBalance = null;
      } else {
        this.byPassBalance = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.autoApproval = null;
      } else {
        this.autoApproval = in.readBoolean();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.byPassBalance = null;
          } else {
            this.byPassBalance = in.readBoolean();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.autoApproval = null;
          } else {
            this.autoApproval = in.readBoolean();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










