/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LocationDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4932946362381283744L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocationDetails\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"geohashs_h3\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"GeoHashH3\",\"fields\":[{\"name\":\"level4\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_4\",\"4\"]},{\"name\":\"level5\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_5\",\"5\"]},{\"name\":\"level6\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_6\",\"6\"]},{\"name\":\"level7\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_7\",\"7\"]},{\"name\":\"level8\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_8\",\"8\"]},{\"name\":\"level9\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"_9\",\"9\"]}]}],\"default\":null},{\"name\":\"lat\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lng\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl0_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl0_label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl1_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl1_label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl2_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl2_label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl3_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lvl3_label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"map_address\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"map_path\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"zone_code\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LocationDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LocationDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LocationDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LocationDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LocationDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LocationDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LocationDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LocationDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LocationDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private org.pipeline.trips.avro.GeoHashH3 geohashs_h3;
  private java.lang.CharSequence lat;
  private java.lang.CharSequence lng;
  private java.lang.CharSequence lvl0_id;
  private java.lang.CharSequence lvl0_label;
  private java.lang.CharSequence lvl1_id;
  private java.lang.CharSequence lvl1_label;
  private java.lang.CharSequence lvl2_id;
  private java.lang.CharSequence lvl2_label;
  private java.lang.CharSequence lvl3_id;
  private java.lang.CharSequence lvl3_label;
  private java.lang.CharSequence map_address;
  private java.lang.CharSequence map_path;
  private java.lang.CharSequence zone_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LocationDetails() {}

  /**
   * All-args constructor.
   * @param geohashs_h3 The new value for geohashs_h3
   * @param lat The new value for lat
   * @param lng The new value for lng
   * @param lvl0_id The new value for lvl0_id
   * @param lvl0_label The new value for lvl0_label
   * @param lvl1_id The new value for lvl1_id
   * @param lvl1_label The new value for lvl1_label
   * @param lvl2_id The new value for lvl2_id
   * @param lvl2_label The new value for lvl2_label
   * @param lvl3_id The new value for lvl3_id
   * @param lvl3_label The new value for lvl3_label
   * @param map_address The new value for map_address
   * @param map_path The new value for map_path
   * @param zone_code The new value for zone_code
   */
  public LocationDetails(org.pipeline.trips.avro.GeoHashH3 geohashs_h3, java.lang.CharSequence lat, java.lang.CharSequence lng, java.lang.CharSequence lvl0_id, java.lang.CharSequence lvl0_label, java.lang.CharSequence lvl1_id, java.lang.CharSequence lvl1_label, java.lang.CharSequence lvl2_id, java.lang.CharSequence lvl2_label, java.lang.CharSequence lvl3_id, java.lang.CharSequence lvl3_label, java.lang.CharSequence map_address, java.lang.CharSequence map_path, java.lang.CharSequence zone_code) {
    this.geohashs_h3 = geohashs_h3;
    this.lat = lat;
    this.lng = lng;
    this.lvl0_id = lvl0_id;
    this.lvl0_label = lvl0_label;
    this.lvl1_id = lvl1_id;
    this.lvl1_label = lvl1_label;
    this.lvl2_id = lvl2_id;
    this.lvl2_label = lvl2_label;
    this.lvl3_id = lvl3_id;
    this.lvl3_label = lvl3_label;
    this.map_address = map_address;
    this.map_path = map_path;
    this.zone_code = zone_code;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return geohashs_h3;
    case 1: return lat;
    case 2: return lng;
    case 3: return lvl0_id;
    case 4: return lvl0_label;
    case 5: return lvl1_id;
    case 6: return lvl1_label;
    case 7: return lvl2_id;
    case 8: return lvl2_label;
    case 9: return lvl3_id;
    case 10: return lvl3_label;
    case 11: return map_address;
    case 12: return map_path;
    case 13: return zone_code;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: geohashs_h3 = (org.pipeline.trips.avro.GeoHashH3)value$; break;
    case 1: lat = (java.lang.CharSequence)value$; break;
    case 2: lng = (java.lang.CharSequence)value$; break;
    case 3: lvl0_id = (java.lang.CharSequence)value$; break;
    case 4: lvl0_label = (java.lang.CharSequence)value$; break;
    case 5: lvl1_id = (java.lang.CharSequence)value$; break;
    case 6: lvl1_label = (java.lang.CharSequence)value$; break;
    case 7: lvl2_id = (java.lang.CharSequence)value$; break;
    case 8: lvl2_label = (java.lang.CharSequence)value$; break;
    case 9: lvl3_id = (java.lang.CharSequence)value$; break;
    case 10: lvl3_label = (java.lang.CharSequence)value$; break;
    case 11: map_address = (java.lang.CharSequence)value$; break;
    case 12: map_path = (java.lang.CharSequence)value$; break;
    case 13: zone_code = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'geohashs_h3' field.
   * @return The value of the 'geohashs_h3' field.
   */
  public org.pipeline.trips.avro.GeoHashH3 getGeohashsH3() {
    return geohashs_h3;
  }


  /**
   * Sets the value of the 'geohashs_h3' field.
   * @param value the value to set.
   */
  public void setGeohashsH3(org.pipeline.trips.avro.GeoHashH3 value) {
    this.geohashs_h3 = value;
  }

  /**
   * Gets the value of the 'lat' field.
   * @return The value of the 'lat' field.
   */
  public java.lang.CharSequence getLat() {
    return lat;
  }


  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(java.lang.CharSequence value) {
    this.lat = value;
  }

  /**
   * Gets the value of the 'lng' field.
   * @return The value of the 'lng' field.
   */
  public java.lang.CharSequence getLng() {
    return lng;
  }


  /**
   * Sets the value of the 'lng' field.
   * @param value the value to set.
   */
  public void setLng(java.lang.CharSequence value) {
    this.lng = value;
  }

  /**
   * Gets the value of the 'lvl0_id' field.
   * @return The value of the 'lvl0_id' field.
   */
  public java.lang.CharSequence getLvl0Id() {
    return lvl0_id;
  }


  /**
   * Sets the value of the 'lvl0_id' field.
   * @param value the value to set.
   */
  public void setLvl0Id(java.lang.CharSequence value) {
    this.lvl0_id = value;
  }

  /**
   * Gets the value of the 'lvl0_label' field.
   * @return The value of the 'lvl0_label' field.
   */
  public java.lang.CharSequence getLvl0Label() {
    return lvl0_label;
  }


  /**
   * Sets the value of the 'lvl0_label' field.
   * @param value the value to set.
   */
  public void setLvl0Label(java.lang.CharSequence value) {
    this.lvl0_label = value;
  }

  /**
   * Gets the value of the 'lvl1_id' field.
   * @return The value of the 'lvl1_id' field.
   */
  public java.lang.CharSequence getLvl1Id() {
    return lvl1_id;
  }


  /**
   * Sets the value of the 'lvl1_id' field.
   * @param value the value to set.
   */
  public void setLvl1Id(java.lang.CharSequence value) {
    this.lvl1_id = value;
  }

  /**
   * Gets the value of the 'lvl1_label' field.
   * @return The value of the 'lvl1_label' field.
   */
  public java.lang.CharSequence getLvl1Label() {
    return lvl1_label;
  }


  /**
   * Sets the value of the 'lvl1_label' field.
   * @param value the value to set.
   */
  public void setLvl1Label(java.lang.CharSequence value) {
    this.lvl1_label = value;
  }

  /**
   * Gets the value of the 'lvl2_id' field.
   * @return The value of the 'lvl2_id' field.
   */
  public java.lang.CharSequence getLvl2Id() {
    return lvl2_id;
  }


  /**
   * Sets the value of the 'lvl2_id' field.
   * @param value the value to set.
   */
  public void setLvl2Id(java.lang.CharSequence value) {
    this.lvl2_id = value;
  }

  /**
   * Gets the value of the 'lvl2_label' field.
   * @return The value of the 'lvl2_label' field.
   */
  public java.lang.CharSequence getLvl2Label() {
    return lvl2_label;
  }


  /**
   * Sets the value of the 'lvl2_label' field.
   * @param value the value to set.
   */
  public void setLvl2Label(java.lang.CharSequence value) {
    this.lvl2_label = value;
  }

  /**
   * Gets the value of the 'lvl3_id' field.
   * @return The value of the 'lvl3_id' field.
   */
  public java.lang.CharSequence getLvl3Id() {
    return lvl3_id;
  }


  /**
   * Sets the value of the 'lvl3_id' field.
   * @param value the value to set.
   */
  public void setLvl3Id(java.lang.CharSequence value) {
    this.lvl3_id = value;
  }

  /**
   * Gets the value of the 'lvl3_label' field.
   * @return The value of the 'lvl3_label' field.
   */
  public java.lang.CharSequence getLvl3Label() {
    return lvl3_label;
  }


  /**
   * Sets the value of the 'lvl3_label' field.
   * @param value the value to set.
   */
  public void setLvl3Label(java.lang.CharSequence value) {
    this.lvl3_label = value;
  }

  /**
   * Gets the value of the 'map_address' field.
   * @return The value of the 'map_address' field.
   */
  public java.lang.CharSequence getMapAddress() {
    return map_address;
  }


  /**
   * Sets the value of the 'map_address' field.
   * @param value the value to set.
   */
  public void setMapAddress(java.lang.CharSequence value) {
    this.map_address = value;
  }

  /**
   * Gets the value of the 'map_path' field.
   * @return The value of the 'map_path' field.
   */
  public java.lang.CharSequence getMapPath() {
    return map_path;
  }


  /**
   * Sets the value of the 'map_path' field.
   * @param value the value to set.
   */
  public void setMapPath(java.lang.CharSequence value) {
    this.map_path = value;
  }

  /**
   * Gets the value of the 'zone_code' field.
   * @return The value of the 'zone_code' field.
   */
  public java.lang.CharSequence getZoneCode() {
    return zone_code;
  }


  /**
   * Sets the value of the 'zone_code' field.
   * @param value the value to set.
   */
  public void setZoneCode(java.lang.CharSequence value) {
    this.zone_code = value;
  }

  /**
   * Creates a new LocationDetails RecordBuilder.
   * @return A new LocationDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.LocationDetails.Builder newBuilder() {
    return new org.pipeline.trips.avro.LocationDetails.Builder();
  }

  /**
   * Creates a new LocationDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LocationDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.LocationDetails.Builder newBuilder(org.pipeline.trips.avro.LocationDetails.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.LocationDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.LocationDetails.Builder(other);
    }
  }

  /**
   * Creates a new LocationDetails RecordBuilder by copying an existing LocationDetails instance.
   * @param other The existing instance to copy.
   * @return A new LocationDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.LocationDetails.Builder newBuilder(org.pipeline.trips.avro.LocationDetails other) {
    if (other == null) {
      return new org.pipeline.trips.avro.LocationDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.LocationDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for LocationDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocationDetails>
    implements org.apache.avro.data.RecordBuilder<LocationDetails> {

    private org.pipeline.trips.avro.GeoHashH3 geohashs_h3;
    private org.pipeline.trips.avro.GeoHashH3.Builder geohashs_h3Builder;
    private java.lang.CharSequence lat;
    private java.lang.CharSequence lng;
    private java.lang.CharSequence lvl0_id;
    private java.lang.CharSequence lvl0_label;
    private java.lang.CharSequence lvl1_id;
    private java.lang.CharSequence lvl1_label;
    private java.lang.CharSequence lvl2_id;
    private java.lang.CharSequence lvl2_label;
    private java.lang.CharSequence lvl3_id;
    private java.lang.CharSequence lvl3_label;
    private java.lang.CharSequence map_address;
    private java.lang.CharSequence map_path;
    private java.lang.CharSequence zone_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.LocationDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.geohashs_h3)) {
        this.geohashs_h3 = data().deepCopy(fields()[0].schema(), other.geohashs_h3);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasGeohashsH3Builder()) {
        this.geohashs_h3Builder = org.pipeline.trips.avro.GeoHashH3.newBuilder(other.getGeohashsH3Builder());
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lng)) {
        this.lng = data().deepCopy(fields()[2].schema(), other.lng);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.lvl0_id)) {
        this.lvl0_id = data().deepCopy(fields()[3].schema(), other.lvl0_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lvl0_label)) {
        this.lvl0_label = data().deepCopy(fields()[4].schema(), other.lvl0_label);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.lvl1_id)) {
        this.lvl1_id = data().deepCopy(fields()[5].schema(), other.lvl1_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.lvl1_label)) {
        this.lvl1_label = data().deepCopy(fields()[6].schema(), other.lvl1_label);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lvl2_id)) {
        this.lvl2_id = data().deepCopy(fields()[7].schema(), other.lvl2_id);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.lvl2_label)) {
        this.lvl2_label = data().deepCopy(fields()[8].schema(), other.lvl2_label);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.lvl3_id)) {
        this.lvl3_id = data().deepCopy(fields()[9].schema(), other.lvl3_id);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.lvl3_label)) {
        this.lvl3_label = data().deepCopy(fields()[10].schema(), other.lvl3_label);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.map_address)) {
        this.map_address = data().deepCopy(fields()[11].schema(), other.map_address);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.map_path)) {
        this.map_path = data().deepCopy(fields()[12].schema(), other.map_path);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.zone_code)) {
        this.zone_code = data().deepCopy(fields()[13].schema(), other.zone_code);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing LocationDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.LocationDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.geohashs_h3)) {
        this.geohashs_h3 = data().deepCopy(fields()[0].schema(), other.geohashs_h3);
        fieldSetFlags()[0] = true;
      }
      this.geohashs_h3Builder = null;
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lng)) {
        this.lng = data().deepCopy(fields()[2].schema(), other.lng);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lvl0_id)) {
        this.lvl0_id = data().deepCopy(fields()[3].schema(), other.lvl0_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lvl0_label)) {
        this.lvl0_label = data().deepCopy(fields()[4].schema(), other.lvl0_label);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lvl1_id)) {
        this.lvl1_id = data().deepCopy(fields()[5].schema(), other.lvl1_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.lvl1_label)) {
        this.lvl1_label = data().deepCopy(fields()[6].schema(), other.lvl1_label);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lvl2_id)) {
        this.lvl2_id = data().deepCopy(fields()[7].schema(), other.lvl2_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lvl2_label)) {
        this.lvl2_label = data().deepCopy(fields()[8].schema(), other.lvl2_label);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lvl3_id)) {
        this.lvl3_id = data().deepCopy(fields()[9].schema(), other.lvl3_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.lvl3_label)) {
        this.lvl3_label = data().deepCopy(fields()[10].schema(), other.lvl3_label);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.map_address)) {
        this.map_address = data().deepCopy(fields()[11].schema(), other.map_address);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.map_path)) {
        this.map_path = data().deepCopy(fields()[12].schema(), other.map_path);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.zone_code)) {
        this.zone_code = data().deepCopy(fields()[13].schema(), other.zone_code);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'geohashs_h3' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.GeoHashH3 getGeohashsH3() {
      return geohashs_h3;
    }


    /**
      * Sets the value of the 'geohashs_h3' field.
      * @param value The value of 'geohashs_h3'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setGeohashsH3(org.pipeline.trips.avro.GeoHashH3 value) {
      validate(fields()[0], value);
      this.geohashs_h3Builder = null;
      this.geohashs_h3 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'geohashs_h3' field has been set.
      * @return True if the 'geohashs_h3' field has been set, false otherwise.
      */
    public boolean hasGeohashsH3() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'geohashs_h3' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.GeoHashH3.Builder getGeohashsH3Builder() {
      if (geohashs_h3Builder == null) {
        if (hasGeohashsH3()) {
          setGeohashsH3Builder(org.pipeline.trips.avro.GeoHashH3.newBuilder(geohashs_h3));
        } else {
          setGeohashsH3Builder(org.pipeline.trips.avro.GeoHashH3.newBuilder());
        }
      }
      return geohashs_h3Builder;
    }

    /**
     * Sets the Builder instance for the 'geohashs_h3' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.LocationDetails.Builder setGeohashsH3Builder(org.pipeline.trips.avro.GeoHashH3.Builder value) {
      clearGeohashsH3();
      geohashs_h3Builder = value;
      return this;
    }

    /**
     * Checks whether the 'geohashs_h3' field has an active Builder instance
     * @return True if the 'geohashs_h3' field has an active Builder instance
     */
    public boolean hasGeohashsH3Builder() {
      return geohashs_h3Builder != null;
    }

    /**
      * Clears the value of the 'geohashs_h3' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearGeohashsH3() {
      geohashs_h3 = null;
      geohashs_h3Builder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lat' field.
      * @return The value.
      */
    public java.lang.CharSequence getLat() {
      return lat;
    }


    /**
      * Sets the value of the 'lat' field.
      * @param value The value of 'lat'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLat(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lat = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lat' field has been set.
      * @return True if the 'lat' field has been set, false otherwise.
      */
    public boolean hasLat() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lat' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLat() {
      lat = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lng' field.
      * @return The value.
      */
    public java.lang.CharSequence getLng() {
      return lng;
    }


    /**
      * Sets the value of the 'lng' field.
      * @param value The value of 'lng'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLng(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lng = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lng' field has been set.
      * @return True if the 'lng' field has been set, false otherwise.
      */
    public boolean hasLng() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lng' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLng() {
      lng = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl0_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl0Id() {
      return lvl0_id;
    }


    /**
      * Sets the value of the 'lvl0_id' field.
      * @param value The value of 'lvl0_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl0Id(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.lvl0_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl0_id' field has been set.
      * @return True if the 'lvl0_id' field has been set, false otherwise.
      */
    public boolean hasLvl0Id() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lvl0_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl0Id() {
      lvl0_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl0_label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl0Label() {
      return lvl0_label;
    }


    /**
      * Sets the value of the 'lvl0_label' field.
      * @param value The value of 'lvl0_label'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl0Label(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.lvl0_label = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl0_label' field has been set.
      * @return True if the 'lvl0_label' field has been set, false otherwise.
      */
    public boolean hasLvl0Label() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lvl0_label' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl0Label() {
      lvl0_label = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl1_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl1Id() {
      return lvl1_id;
    }


    /**
      * Sets the value of the 'lvl1_id' field.
      * @param value The value of 'lvl1_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl1Id(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.lvl1_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl1_id' field has been set.
      * @return True if the 'lvl1_id' field has been set, false otherwise.
      */
    public boolean hasLvl1Id() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lvl1_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl1Id() {
      lvl1_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl1_label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl1Label() {
      return lvl1_label;
    }


    /**
      * Sets the value of the 'lvl1_label' field.
      * @param value The value of 'lvl1_label'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl1Label(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.lvl1_label = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl1_label' field has been set.
      * @return True if the 'lvl1_label' field has been set, false otherwise.
      */
    public boolean hasLvl1Label() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'lvl1_label' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl1Label() {
      lvl1_label = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl2_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl2Id() {
      return lvl2_id;
    }


    /**
      * Sets the value of the 'lvl2_id' field.
      * @param value The value of 'lvl2_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl2Id(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.lvl2_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl2_id' field has been set.
      * @return True if the 'lvl2_id' field has been set, false otherwise.
      */
    public boolean hasLvl2Id() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lvl2_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl2Id() {
      lvl2_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl2_label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl2Label() {
      return lvl2_label;
    }


    /**
      * Sets the value of the 'lvl2_label' field.
      * @param value The value of 'lvl2_label'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl2Label(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.lvl2_label = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl2_label' field has been set.
      * @return True if the 'lvl2_label' field has been set, false otherwise.
      */
    public boolean hasLvl2Label() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'lvl2_label' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl2Label() {
      lvl2_label = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl3_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl3Id() {
      return lvl3_id;
    }


    /**
      * Sets the value of the 'lvl3_id' field.
      * @param value The value of 'lvl3_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl3Id(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.lvl3_id = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl3_id' field has been set.
      * @return True if the 'lvl3_id' field has been set, false otherwise.
      */
    public boolean hasLvl3Id() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'lvl3_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl3Id() {
      lvl3_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'lvl3_label' field.
      * @return The value.
      */
    public java.lang.CharSequence getLvl3Label() {
      return lvl3_label;
    }


    /**
      * Sets the value of the 'lvl3_label' field.
      * @param value The value of 'lvl3_label'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setLvl3Label(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.lvl3_label = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'lvl3_label' field has been set.
      * @return True if the 'lvl3_label' field has been set, false otherwise.
      */
    public boolean hasLvl3Label() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'lvl3_label' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearLvl3Label() {
      lvl3_label = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'map_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getMapAddress() {
      return map_address;
    }


    /**
      * Sets the value of the 'map_address' field.
      * @param value The value of 'map_address'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setMapAddress(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.map_address = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'map_address' field has been set.
      * @return True if the 'map_address' field has been set, false otherwise.
      */
    public boolean hasMapAddress() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'map_address' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearMapAddress() {
      map_address = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'map_path' field.
      * @return The value.
      */
    public java.lang.CharSequence getMapPath() {
      return map_path;
    }


    /**
      * Sets the value of the 'map_path' field.
      * @param value The value of 'map_path'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setMapPath(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.map_path = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'map_path' field has been set.
      * @return True if the 'map_path' field has been set, false otherwise.
      */
    public boolean hasMapPath() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'map_path' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearMapPath() {
      map_path = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'zone_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getZoneCode() {
      return zone_code;
    }


    /**
      * Sets the value of the 'zone_code' field.
      * @param value The value of 'zone_code'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder setZoneCode(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.zone_code = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'zone_code' field has been set.
      * @return True if the 'zone_code' field has been set, false otherwise.
      */
    public boolean hasZoneCode() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'zone_code' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.LocationDetails.Builder clearZoneCode() {
      zone_code = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LocationDetails build() {
      try {
        LocationDetails record = new LocationDetails();
        if (geohashs_h3Builder != null) {
          try {
            record.geohashs_h3 = this.geohashs_h3Builder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("geohashs_h3"));
            throw e;
          }
        } else {
          record.geohashs_h3 = fieldSetFlags()[0] ? this.geohashs_h3 : (org.pipeline.trips.avro.GeoHashH3) defaultValue(fields()[0]);
        }
        record.lat = fieldSetFlags()[1] ? this.lat : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lng = fieldSetFlags()[2] ? this.lng : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.lvl0_id = fieldSetFlags()[3] ? this.lvl0_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.lvl0_label = fieldSetFlags()[4] ? this.lvl0_label : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.lvl1_id = fieldSetFlags()[5] ? this.lvl1_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.lvl1_label = fieldSetFlags()[6] ? this.lvl1_label : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.lvl2_id = fieldSetFlags()[7] ? this.lvl2_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.lvl2_label = fieldSetFlags()[8] ? this.lvl2_label : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.lvl3_id = fieldSetFlags()[9] ? this.lvl3_id : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.lvl3_label = fieldSetFlags()[10] ? this.lvl3_label : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.map_address = fieldSetFlags()[11] ? this.map_address : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.map_path = fieldSetFlags()[12] ? this.map_path : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.zone_code = fieldSetFlags()[13] ? this.zone_code : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LocationDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<LocationDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LocationDetails>
    READER$ = (org.apache.avro.io.DatumReader<LocationDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.geohashs_h3 == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.geohashs_h3.customEncode(out);
    }

    if (this.lat == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lat);
    }

    if (this.lng == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lng);
    }

    if (this.lvl0_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl0_id);
    }

    if (this.lvl0_label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl0_label);
    }

    if (this.lvl1_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl1_id);
    }

    if (this.lvl1_label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl1_label);
    }

    if (this.lvl2_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl2_id);
    }

    if (this.lvl2_label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl2_label);
    }

    if (this.lvl3_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl3_id);
    }

    if (this.lvl3_label == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lvl3_label);
    }

    if (this.map_address == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.map_address);
    }

    if (this.map_path == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.map_path);
    }

    if (this.zone_code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.zone_code);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.geohashs_h3 = null;
      } else {
        if (this.geohashs_h3 == null) {
          this.geohashs_h3 = new org.pipeline.trips.avro.GeoHashH3();
        }
        this.geohashs_h3.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lat = null;
      } else {
        this.lat = in.readString(this.lat instanceof Utf8 ? (Utf8)this.lat : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lng = null;
      } else {
        this.lng = in.readString(this.lng instanceof Utf8 ? (Utf8)this.lng : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl0_id = null;
      } else {
        this.lvl0_id = in.readString(this.lvl0_id instanceof Utf8 ? (Utf8)this.lvl0_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl0_label = null;
      } else {
        this.lvl0_label = in.readString(this.lvl0_label instanceof Utf8 ? (Utf8)this.lvl0_label : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl1_id = null;
      } else {
        this.lvl1_id = in.readString(this.lvl1_id instanceof Utf8 ? (Utf8)this.lvl1_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl1_label = null;
      } else {
        this.lvl1_label = in.readString(this.lvl1_label instanceof Utf8 ? (Utf8)this.lvl1_label : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl2_id = null;
      } else {
        this.lvl2_id = in.readString(this.lvl2_id instanceof Utf8 ? (Utf8)this.lvl2_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl2_label = null;
      } else {
        this.lvl2_label = in.readString(this.lvl2_label instanceof Utf8 ? (Utf8)this.lvl2_label : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl3_id = null;
      } else {
        this.lvl3_id = in.readString(this.lvl3_id instanceof Utf8 ? (Utf8)this.lvl3_id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lvl3_label = null;
      } else {
        this.lvl3_label = in.readString(this.lvl3_label instanceof Utf8 ? (Utf8)this.lvl3_label : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.map_address = null;
      } else {
        this.map_address = in.readString(this.map_address instanceof Utf8 ? (Utf8)this.map_address : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.map_path = null;
      } else {
        this.map_path = in.readString(this.map_path instanceof Utf8 ? (Utf8)this.map_path : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.zone_code = null;
      } else {
        this.zone_code = in.readString(this.zone_code instanceof Utf8 ? (Utf8)this.zone_code : null);
      }

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.geohashs_h3 = null;
          } else {
            if (this.geohashs_h3 == null) {
              this.geohashs_h3 = new org.pipeline.trips.avro.GeoHashH3();
            }
            this.geohashs_h3.customDecode(in);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lat = null;
          } else {
            this.lat = in.readString(this.lat instanceof Utf8 ? (Utf8)this.lat : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lng = null;
          } else {
            this.lng = in.readString(this.lng instanceof Utf8 ? (Utf8)this.lng : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl0_id = null;
          } else {
            this.lvl0_id = in.readString(this.lvl0_id instanceof Utf8 ? (Utf8)this.lvl0_id : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl0_label = null;
          } else {
            this.lvl0_label = in.readString(this.lvl0_label instanceof Utf8 ? (Utf8)this.lvl0_label : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl1_id = null;
          } else {
            this.lvl1_id = in.readString(this.lvl1_id instanceof Utf8 ? (Utf8)this.lvl1_id : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl1_label = null;
          } else {
            this.lvl1_label = in.readString(this.lvl1_label instanceof Utf8 ? (Utf8)this.lvl1_label : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl2_id = null;
          } else {
            this.lvl2_id = in.readString(this.lvl2_id instanceof Utf8 ? (Utf8)this.lvl2_id : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl2_label = null;
          } else {
            this.lvl2_label = in.readString(this.lvl2_label instanceof Utf8 ? (Utf8)this.lvl2_label : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl3_id = null;
          } else {
            this.lvl3_id = in.readString(this.lvl3_id instanceof Utf8 ? (Utf8)this.lvl3_id : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lvl3_label = null;
          } else {
            this.lvl3_label = in.readString(this.lvl3_label instanceof Utf8 ? (Utf8)this.lvl3_label : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.map_address = null;
          } else {
            this.map_address = in.readString(this.map_address instanceof Utf8 ? (Utf8)this.map_address : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.map_path = null;
          } else {
            this.map_path = in.readString(this.map_path instanceof Utf8 ? (Utf8)this.map_path : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.zone_code = null;
          } else {
            this.zone_code = in.readString(this.zone_code instanceof Utf8 ? (Utf8)this.zone_code : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










