/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProgressDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7696251505900847383L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProgressDetails\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"accuracy\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"bearing\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"direction_updated_at\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"estimated_arrival_time\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"estimated_distance\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"estimated_time\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"polyline\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"speed\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProgressDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProgressDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProgressDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProgressDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProgressDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProgressDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProgressDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProgressDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProgressDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Double accuracy;
  private java.lang.Double bearing;
  private java.time.Instant direction_updated_at;
  private java.time.Instant estimated_arrival_time;
  private java.lang.Integer estimated_distance;
  private java.lang.Integer estimated_time;
  private java.lang.CharSequence polyline;
  private java.lang.Double speed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProgressDetails() {}

  /**
   * All-args constructor.
   * @param accuracy The new value for accuracy
   * @param bearing The new value for bearing
   * @param direction_updated_at The new value for direction_updated_at
   * @param estimated_arrival_time The new value for estimated_arrival_time
   * @param estimated_distance The new value for estimated_distance
   * @param estimated_time The new value for estimated_time
   * @param polyline The new value for polyline
   * @param speed The new value for speed
   */
  public ProgressDetails(java.lang.Double accuracy, java.lang.Double bearing, java.time.Instant direction_updated_at, java.time.Instant estimated_arrival_time, java.lang.Integer estimated_distance, java.lang.Integer estimated_time, java.lang.CharSequence polyline, java.lang.Double speed) {
    this.accuracy = accuracy;
    this.bearing = bearing;
    this.direction_updated_at = direction_updated_at;
    this.estimated_arrival_time = estimated_arrival_time;
    this.estimated_distance = estimated_distance;
    this.estimated_time = estimated_time;
    this.polyline = polyline;
    this.speed = speed;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return accuracy;
    case 1: return bearing;
    case 2: return direction_updated_at;
    case 3: return estimated_arrival_time;
    case 4: return estimated_distance;
    case 5: return estimated_time;
    case 6: return polyline;
    case 7: return speed;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: accuracy = (java.lang.Double)value$; break;
    case 1: bearing = (java.lang.Double)value$; break;
    case 2: direction_updated_at = (java.time.Instant)value$; break;
    case 3: estimated_arrival_time = (java.time.Instant)value$; break;
    case 4: estimated_distance = (java.lang.Integer)value$; break;
    case 5: estimated_time = (java.lang.Integer)value$; break;
    case 6: polyline = (java.lang.CharSequence)value$; break;
    case 7: speed = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'accuracy' field.
   * @return The value of the 'accuracy' field.
   */
  public java.lang.Double getAccuracy() {
    return accuracy;
  }


  /**
   * Sets the value of the 'accuracy' field.
   * @param value the value to set.
   */
  public void setAccuracy(java.lang.Double value) {
    this.accuracy = value;
  }

  /**
   * Gets the value of the 'bearing' field.
   * @return The value of the 'bearing' field.
   */
  public java.lang.Double getBearing() {
    return bearing;
  }


  /**
   * Sets the value of the 'bearing' field.
   * @param value the value to set.
   */
  public void setBearing(java.lang.Double value) {
    this.bearing = value;
  }

  /**
   * Gets the value of the 'direction_updated_at' field.
   * @return The value of the 'direction_updated_at' field.
   */
  public java.time.Instant getDirectionUpdatedAt() {
    return direction_updated_at;
  }


  /**
   * Sets the value of the 'direction_updated_at' field.
   * @param value the value to set.
   */
  public void setDirectionUpdatedAt(java.time.Instant value) {
    this.direction_updated_at = value;
  }

  /**
   * Gets the value of the 'estimated_arrival_time' field.
   * @return The value of the 'estimated_arrival_time' field.
   */
  public java.time.Instant getEstimatedArrivalTime() {
    return estimated_arrival_time;
  }


  /**
   * Sets the value of the 'estimated_arrival_time' field.
   * @param value the value to set.
   */
  public void setEstimatedArrivalTime(java.time.Instant value) {
    this.estimated_arrival_time = value;
  }

  /**
   * Gets the value of the 'estimated_distance' field.
   * @return The value of the 'estimated_distance' field.
   */
  public java.lang.Integer getEstimatedDistance() {
    return estimated_distance;
  }


  /**
   * Sets the value of the 'estimated_distance' field.
   * @param value the value to set.
   */
  public void setEstimatedDistance(java.lang.Integer value) {
    this.estimated_distance = value;
  }

  /**
   * Gets the value of the 'estimated_time' field.
   * @return The value of the 'estimated_time' field.
   */
  public java.lang.Integer getEstimatedTime() {
    return estimated_time;
  }


  /**
   * Sets the value of the 'estimated_time' field.
   * @param value the value to set.
   */
  public void setEstimatedTime(java.lang.Integer value) {
    this.estimated_time = value;
  }

  /**
   * Gets the value of the 'polyline' field.
   * @return The value of the 'polyline' field.
   */
  public java.lang.CharSequence getPolyline() {
    return polyline;
  }


  /**
   * Sets the value of the 'polyline' field.
   * @param value the value to set.
   */
  public void setPolyline(java.lang.CharSequence value) {
    this.polyline = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return The value of the 'speed' field.
   */
  public java.lang.Double getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * @param value the value to set.
   */
  public void setSpeed(java.lang.Double value) {
    this.speed = value;
  }

  /**
   * Creates a new ProgressDetails RecordBuilder.
   * @return A new ProgressDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.ProgressDetails.Builder newBuilder() {
    return new org.pipeline.trips.avro.ProgressDetails.Builder();
  }

  /**
   * Creates a new ProgressDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProgressDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.ProgressDetails.Builder newBuilder(org.pipeline.trips.avro.ProgressDetails.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.ProgressDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.ProgressDetails.Builder(other);
    }
  }

  /**
   * Creates a new ProgressDetails RecordBuilder by copying an existing ProgressDetails instance.
   * @param other The existing instance to copy.
   * @return A new ProgressDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.ProgressDetails.Builder newBuilder(org.pipeline.trips.avro.ProgressDetails other) {
    if (other == null) {
      return new org.pipeline.trips.avro.ProgressDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.ProgressDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProgressDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProgressDetails>
    implements org.apache.avro.data.RecordBuilder<ProgressDetails> {

    private java.lang.Double accuracy;
    private java.lang.Double bearing;
    private java.time.Instant direction_updated_at;
    private java.time.Instant estimated_arrival_time;
    private java.lang.Integer estimated_distance;
    private java.lang.Integer estimated_time;
    private java.lang.CharSequence polyline;
    private java.lang.Double speed;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.ProgressDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.accuracy)) {
        this.accuracy = data().deepCopy(fields()[0].schema(), other.accuracy);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bearing)) {
        this.bearing = data().deepCopy(fields()[1].schema(), other.bearing);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.direction_updated_at)) {
        this.direction_updated_at = data().deepCopy(fields()[2].schema(), other.direction_updated_at);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.estimated_arrival_time)) {
        this.estimated_arrival_time = data().deepCopy(fields()[3].schema(), other.estimated_arrival_time);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.estimated_distance)) {
        this.estimated_distance = data().deepCopy(fields()[4].schema(), other.estimated_distance);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.estimated_time)) {
        this.estimated_time = data().deepCopy(fields()[5].schema(), other.estimated_time);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.polyline)) {
        this.polyline = data().deepCopy(fields()[6].schema(), other.polyline);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.speed)) {
        this.speed = data().deepCopy(fields()[7].schema(), other.speed);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing ProgressDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.ProgressDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.accuracy)) {
        this.accuracy = data().deepCopy(fields()[0].schema(), other.accuracy);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bearing)) {
        this.bearing = data().deepCopy(fields()[1].schema(), other.bearing);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.direction_updated_at)) {
        this.direction_updated_at = data().deepCopy(fields()[2].schema(), other.direction_updated_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.estimated_arrival_time)) {
        this.estimated_arrival_time = data().deepCopy(fields()[3].schema(), other.estimated_arrival_time);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.estimated_distance)) {
        this.estimated_distance = data().deepCopy(fields()[4].schema(), other.estimated_distance);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.estimated_time)) {
        this.estimated_time = data().deepCopy(fields()[5].schema(), other.estimated_time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.polyline)) {
        this.polyline = data().deepCopy(fields()[6].schema(), other.polyline);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.speed)) {
        this.speed = data().deepCopy(fields()[7].schema(), other.speed);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'accuracy' field.
      * @return The value.
      */
    public java.lang.Double getAccuracy() {
      return accuracy;
    }


    /**
      * Sets the value of the 'accuracy' field.
      * @param value The value of 'accuracy'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setAccuracy(java.lang.Double value) {
      validate(fields()[0], value);
      this.accuracy = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'accuracy' field has been set.
      * @return True if the 'accuracy' field has been set, false otherwise.
      */
    public boolean hasAccuracy() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'accuracy' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearAccuracy() {
      accuracy = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bearing' field.
      * @return The value.
      */
    public java.lang.Double getBearing() {
      return bearing;
    }


    /**
      * Sets the value of the 'bearing' field.
      * @param value The value of 'bearing'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setBearing(java.lang.Double value) {
      validate(fields()[1], value);
      this.bearing = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bearing' field has been set.
      * @return True if the 'bearing' field has been set, false otherwise.
      */
    public boolean hasBearing() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bearing' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearBearing() {
      bearing = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'direction_updated_at' field.
      * @return The value.
      */
    public java.time.Instant getDirectionUpdatedAt() {
      return direction_updated_at;
    }


    /**
      * Sets the value of the 'direction_updated_at' field.
      * @param value The value of 'direction_updated_at'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setDirectionUpdatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.direction_updated_at = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'direction_updated_at' field has been set.
      * @return True if the 'direction_updated_at' field has been set, false otherwise.
      */
    public boolean hasDirectionUpdatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'direction_updated_at' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearDirectionUpdatedAt() {
      direction_updated_at = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'estimated_arrival_time' field.
      * @return The value.
      */
    public java.time.Instant getEstimatedArrivalTime() {
      return estimated_arrival_time;
    }


    /**
      * Sets the value of the 'estimated_arrival_time' field.
      * @param value The value of 'estimated_arrival_time'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setEstimatedArrivalTime(java.time.Instant value) {
      validate(fields()[3], value);
      this.estimated_arrival_time = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'estimated_arrival_time' field has been set.
      * @return True if the 'estimated_arrival_time' field has been set, false otherwise.
      */
    public boolean hasEstimatedArrivalTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'estimated_arrival_time' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearEstimatedArrivalTime() {
      estimated_arrival_time = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'estimated_distance' field.
      * @return The value.
      */
    public java.lang.Integer getEstimatedDistance() {
      return estimated_distance;
    }


    /**
      * Sets the value of the 'estimated_distance' field.
      * @param value The value of 'estimated_distance'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setEstimatedDistance(java.lang.Integer value) {
      validate(fields()[4], value);
      this.estimated_distance = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'estimated_distance' field has been set.
      * @return True if the 'estimated_distance' field has been set, false otherwise.
      */
    public boolean hasEstimatedDistance() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'estimated_distance' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearEstimatedDistance() {
      estimated_distance = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'estimated_time' field.
      * @return The value.
      */
    public java.lang.Integer getEstimatedTime() {
      return estimated_time;
    }


    /**
      * Sets the value of the 'estimated_time' field.
      * @param value The value of 'estimated_time'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setEstimatedTime(java.lang.Integer value) {
      validate(fields()[5], value);
      this.estimated_time = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'estimated_time' field has been set.
      * @return True if the 'estimated_time' field has been set, false otherwise.
      */
    public boolean hasEstimatedTime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'estimated_time' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearEstimatedTime() {
      estimated_time = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'polyline' field.
      * @return The value.
      */
    public java.lang.CharSequence getPolyline() {
      return polyline;
    }


    /**
      * Sets the value of the 'polyline' field.
      * @param value The value of 'polyline'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setPolyline(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.polyline = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'polyline' field has been set.
      * @return True if the 'polyline' field has been set, false otherwise.
      */
    public boolean hasPolyline() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'polyline' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearPolyline() {
      polyline = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * @return The value.
      */
    public java.lang.Double getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder setSpeed(java.lang.Double value) {
      validate(fields()[7], value);
      this.speed = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'speed' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.ProgressDetails.Builder clearSpeed() {
      speed = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProgressDetails build() {
      try {
        ProgressDetails record = new ProgressDetails();
        record.accuracy = fieldSetFlags()[0] ? this.accuracy : (java.lang.Double) defaultValue(fields()[0]);
        record.bearing = fieldSetFlags()[1] ? this.bearing : (java.lang.Double) defaultValue(fields()[1]);
        record.direction_updated_at = fieldSetFlags()[2] ? this.direction_updated_at : (java.time.Instant) defaultValue(fields()[2]);
        record.estimated_arrival_time = fieldSetFlags()[3] ? this.estimated_arrival_time : (java.time.Instant) defaultValue(fields()[3]);
        record.estimated_distance = fieldSetFlags()[4] ? this.estimated_distance : (java.lang.Integer) defaultValue(fields()[4]);
        record.estimated_time = fieldSetFlags()[5] ? this.estimated_time : (java.lang.Integer) defaultValue(fields()[5]);
        record.polyline = fieldSetFlags()[6] ? this.polyline : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.speed = fieldSetFlags()[7] ? this.speed : (java.lang.Double) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProgressDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProgressDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProgressDetails>
    READER$ = (org.apache.avro.io.DatumReader<ProgressDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










