/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RiderReview extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4308604212875019137L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RiderReview\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"comment\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"predefined_comments\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"rating\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RiderReview> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RiderReview> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RiderReview> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RiderReview> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RiderReview> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RiderReview to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RiderReview from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RiderReview instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RiderReview fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence comment;
  private java.util.List<java.lang.CharSequence> predefined_comments;
  private java.lang.Integer rating;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RiderReview() {}

  /**
   * All-args constructor.
   * @param comment The new value for comment
   * @param predefined_comments The new value for predefined_comments
   * @param rating The new value for rating
   */
  public RiderReview(java.lang.CharSequence comment, java.util.List<java.lang.CharSequence> predefined_comments, java.lang.Integer rating) {
    this.comment = comment;
    this.predefined_comments = predefined_comments;
    this.rating = rating;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return comment;
    case 1: return predefined_comments;
    case 2: return rating;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: comment = (java.lang.CharSequence)value$; break;
    case 1: predefined_comments = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: rating = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'comment' field.
   * @return The value of the 'comment' field.
   */
  public java.lang.CharSequence getComment() {
    return comment;
  }


  /**
   * Sets the value of the 'comment' field.
   * @param value the value to set.
   */
  public void setComment(java.lang.CharSequence value) {
    this.comment = value;
  }

  /**
   * Gets the value of the 'predefined_comments' field.
   * @return The value of the 'predefined_comments' field.
   */
  public java.util.List<java.lang.CharSequence> getPredefinedComments() {
    return predefined_comments;
  }


  /**
   * Sets the value of the 'predefined_comments' field.
   * @param value the value to set.
   */
  public void setPredefinedComments(java.util.List<java.lang.CharSequence> value) {
    this.predefined_comments = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public java.lang.Integer getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(java.lang.Integer value) {
    this.rating = value;
  }

  /**
   * Creates a new RiderReview RecordBuilder.
   * @return A new RiderReview RecordBuilder
   */
  public static org.pipeline.trips.avro.RiderReview.Builder newBuilder() {
    return new org.pipeline.trips.avro.RiderReview.Builder();
  }

  /**
   * Creates a new RiderReview RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RiderReview RecordBuilder
   */
  public static org.pipeline.trips.avro.RiderReview.Builder newBuilder(org.pipeline.trips.avro.RiderReview.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.RiderReview.Builder();
    } else {
      return new org.pipeline.trips.avro.RiderReview.Builder(other);
    }
  }

  /**
   * Creates a new RiderReview RecordBuilder by copying an existing RiderReview instance.
   * @param other The existing instance to copy.
   * @return A new RiderReview RecordBuilder
   */
  public static org.pipeline.trips.avro.RiderReview.Builder newBuilder(org.pipeline.trips.avro.RiderReview other) {
    if (other == null) {
      return new org.pipeline.trips.avro.RiderReview.Builder();
    } else {
      return new org.pipeline.trips.avro.RiderReview.Builder(other);
    }
  }

  /**
   * RecordBuilder for RiderReview instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RiderReview>
    implements org.apache.avro.data.RecordBuilder<RiderReview> {

    private java.lang.CharSequence comment;
    private java.util.List<java.lang.CharSequence> predefined_comments;
    private java.lang.Integer rating;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.RiderReview.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.comment)) {
        this.comment = data().deepCopy(fields()[0].schema(), other.comment);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.predefined_comments)) {
        this.predefined_comments = data().deepCopy(fields()[1].schema(), other.predefined_comments);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RiderReview instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.RiderReview other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.comment)) {
        this.comment = data().deepCopy(fields()[0].schema(), other.comment);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.predefined_comments)) {
        this.predefined_comments = data().deepCopy(fields()[1].schema(), other.predefined_comments);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'comment' field.
      * @return The value.
      */
    public java.lang.CharSequence getComment() {
      return comment;
    }


    /**
      * Sets the value of the 'comment' field.
      * @param value The value of 'comment'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder setComment(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.comment = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'comment' field has been set.
      * @return True if the 'comment' field has been set, false otherwise.
      */
    public boolean hasComment() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'comment' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder clearComment() {
      comment = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'predefined_comments' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getPredefinedComments() {
      return predefined_comments;
    }


    /**
      * Sets the value of the 'predefined_comments' field.
      * @param value The value of 'predefined_comments'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder setPredefinedComments(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.predefined_comments = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'predefined_comments' field has been set.
      * @return True if the 'predefined_comments' field has been set, false otherwise.
      */
    public boolean hasPredefinedComments() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'predefined_comments' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder clearPredefinedComments() {
      predefined_comments = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public java.lang.Integer getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder setRating(java.lang.Integer value) {
      validate(fields()[2], value);
      this.rating = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.RiderReview.Builder clearRating() {
      rating = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RiderReview build() {
      try {
        RiderReview record = new RiderReview();
        record.comment = fieldSetFlags()[0] ? this.comment : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.predefined_comments = fieldSetFlags()[1] ? this.predefined_comments : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.rating = fieldSetFlags()[2] ? this.rating : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RiderReview>
    WRITER$ = (org.apache.avro.io.DatumWriter<RiderReview>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RiderReview>
    READER$ = (org.apache.avro.io.DatumReader<RiderReview>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.comment == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.comment);
    }

    if (this.predefined_comments == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.predefined_comments.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.CharSequence e0: this.predefined_comments) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.rating == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.rating);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.comment = null;
      } else {
        this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.predefined_comments = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.CharSequence> a0 = this.predefined_comments;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("predefined_comments").schema().getTypes().get(1));
          this.predefined_comments = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
            a0.add(e0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.rating = null;
      } else {
        this.rating = in.readInt();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.comment = null;
          } else {
            this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.predefined_comments = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.CharSequence> a0 = this.predefined_comments;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("predefined_comments").schema().getTypes().get(1));
              this.predefined_comments = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
                a0.add(e0);
              }
            }
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rating = null;
          } else {
            this.rating = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










