/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StatusHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5457592761135874979L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StatusHistory\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"status_history_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"driver\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"insertFrom\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"location\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DriverLocation\",\"fields\":[{\"name\":\"lat\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"lng\",\"type\":[\"null\",\"double\"],\"default\":null}]}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"time\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<StatusHistory> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StatusHistory> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StatusHistory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StatusHistory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StatusHistory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StatusHistory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StatusHistory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StatusHistory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StatusHistory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence status_history_id;
  private java.lang.CharSequence driver;
  private java.lang.CharSequence insertFrom;
  private org.pipeline.trips.avro.DriverLocation location;
  private java.lang.CharSequence status;
  private java.time.Instant time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StatusHistory() {}

  /**
   * All-args constructor.
   * @param status_history_id The new value for status_history_id
   * @param driver The new value for driver
   * @param insertFrom The new value for insertFrom
   * @param location The new value for location
   * @param status The new value for status
   * @param time The new value for time
   */
  public StatusHistory(java.lang.CharSequence status_history_id, java.lang.CharSequence driver, java.lang.CharSequence insertFrom, org.pipeline.trips.avro.DriverLocation location, java.lang.CharSequence status, java.time.Instant time) {
    this.status_history_id = status_history_id;
    this.driver = driver;
    this.insertFrom = insertFrom;
    this.location = location;
    this.status = status;
    this.time = time;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status_history_id;
    case 1: return driver;
    case 2: return insertFrom;
    case 3: return location;
    case 4: return status;
    case 5: return time;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status_history_id = (java.lang.CharSequence)value$; break;
    case 1: driver = (java.lang.CharSequence)value$; break;
    case 2: insertFrom = (java.lang.CharSequence)value$; break;
    case 3: location = (org.pipeline.trips.avro.DriverLocation)value$; break;
    case 4: status = (java.lang.CharSequence)value$; break;
    case 5: time = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status_history_id' field.
   * @return The value of the 'status_history_id' field.
   */
  public java.lang.CharSequence getStatusHistoryId() {
    return status_history_id;
  }


  /**
   * Sets the value of the 'status_history_id' field.
   * @param value the value to set.
   */
  public void setStatusHistoryId(java.lang.CharSequence value) {
    this.status_history_id = value;
  }

  /**
   * Gets the value of the 'driver' field.
   * @return The value of the 'driver' field.
   */
  public java.lang.CharSequence getDriver() {
    return driver;
  }


  /**
   * Sets the value of the 'driver' field.
   * @param value the value to set.
   */
  public void setDriver(java.lang.CharSequence value) {
    this.driver = value;
  }

  /**
   * Gets the value of the 'insertFrom' field.
   * @return The value of the 'insertFrom' field.
   */
  public java.lang.CharSequence getInsertFrom() {
    return insertFrom;
  }


  /**
   * Sets the value of the 'insertFrom' field.
   * @param value the value to set.
   */
  public void setInsertFrom(java.lang.CharSequence value) {
    this.insertFrom = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public org.pipeline.trips.avro.DriverLocation getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(org.pipeline.trips.avro.DriverLocation value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.time.Instant getTime() {
    return time;
  }


  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.time.Instant value) {
    this.time = value;
  }

  /**
   * Creates a new StatusHistory RecordBuilder.
   * @return A new StatusHistory RecordBuilder
   */
  public static org.pipeline.trips.avro.StatusHistory.Builder newBuilder() {
    return new org.pipeline.trips.avro.StatusHistory.Builder();
  }

  /**
   * Creates a new StatusHistory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StatusHistory RecordBuilder
   */
  public static org.pipeline.trips.avro.StatusHistory.Builder newBuilder(org.pipeline.trips.avro.StatusHistory.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.StatusHistory.Builder();
    } else {
      return new org.pipeline.trips.avro.StatusHistory.Builder(other);
    }
  }

  /**
   * Creates a new StatusHistory RecordBuilder by copying an existing StatusHistory instance.
   * @param other The existing instance to copy.
   * @return A new StatusHistory RecordBuilder
   */
  public static org.pipeline.trips.avro.StatusHistory.Builder newBuilder(org.pipeline.trips.avro.StatusHistory other) {
    if (other == null) {
      return new org.pipeline.trips.avro.StatusHistory.Builder();
    } else {
      return new org.pipeline.trips.avro.StatusHistory.Builder(other);
    }
  }

  /**
   * RecordBuilder for StatusHistory instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StatusHistory>
    implements org.apache.avro.data.RecordBuilder<StatusHistory> {

    private java.lang.CharSequence status_history_id;
    private java.lang.CharSequence driver;
    private java.lang.CharSequence insertFrom;
    private org.pipeline.trips.avro.DriverLocation location;
    private org.pipeline.trips.avro.DriverLocation.Builder locationBuilder;
    private java.lang.CharSequence status;
    private java.time.Instant time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.StatusHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status_history_id)) {
        this.status_history_id = data().deepCopy(fields()[0].schema(), other.status_history_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.driver)) {
        this.driver = data().deepCopy(fields()[1].schema(), other.driver);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.insertFrom)) {
        this.insertFrom = data().deepCopy(fields()[2].schema(), other.insertFrom);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.location)) {
        this.location = data().deepCopy(fields()[3].schema(), other.location);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = org.pipeline.trips.avro.DriverLocation.newBuilder(other.getLocationBuilder());
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.time)) {
        this.time = data().deepCopy(fields()[5].schema(), other.time);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing StatusHistory instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.StatusHistory other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.status_history_id)) {
        this.status_history_id = data().deepCopy(fields()[0].schema(), other.status_history_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.driver)) {
        this.driver = data().deepCopy(fields()[1].schema(), other.driver);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.insertFrom)) {
        this.insertFrom = data().deepCopy(fields()[2].schema(), other.insertFrom);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.location)) {
        this.location = data().deepCopy(fields()[3].schema(), other.location);
        fieldSetFlags()[3] = true;
      }
      this.locationBuilder = null;
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.time)) {
        this.time = data().deepCopy(fields()[5].schema(), other.time);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'status_history_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusHistoryId() {
      return status_history_id;
    }


    /**
      * Sets the value of the 'status_history_id' field.
      * @param value The value of 'status_history_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setStatusHistoryId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.status_history_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status_history_id' field has been set.
      * @return True if the 'status_history_id' field has been set, false otherwise.
      */
    public boolean hasStatusHistoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status_history_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearStatusHistoryId() {
      status_history_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'driver' field.
      * @return The value.
      */
    public java.lang.CharSequence getDriver() {
      return driver;
    }


    /**
      * Sets the value of the 'driver' field.
      * @param value The value of 'driver'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setDriver(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.driver = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'driver' field has been set.
      * @return True if the 'driver' field has been set, false otherwise.
      */
    public boolean hasDriver() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'driver' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearDriver() {
      driver = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'insertFrom' field.
      * @return The value.
      */
    public java.lang.CharSequence getInsertFrom() {
      return insertFrom;
    }


    /**
      * Sets the value of the 'insertFrom' field.
      * @param value The value of 'insertFrom'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setInsertFrom(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.insertFrom = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'insertFrom' field has been set.
      * @return True if the 'insertFrom' field has been set, false otherwise.
      */
    public boolean hasInsertFrom() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'insertFrom' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearInsertFrom() {
      insertFrom = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.DriverLocation getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setLocation(org.pipeline.trips.avro.DriverLocation value) {
      validate(fields()[3], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.DriverLocation.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(org.pipeline.trips.avro.DriverLocation.newBuilder(location));
        } else {
          setLocationBuilder(org.pipeline.trips.avro.DriverLocation.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.StatusHistory.Builder setLocationBuilder(org.pipeline.trips.avro.DriverLocation.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.time.Instant getTime() {
      return time;
    }


    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder setTime(java.time.Instant value) {
      validate(fields()[5], value);
      this.time = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StatusHistory.Builder clearTime() {
      time = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StatusHistory build() {
      try {
        StatusHistory record = new StatusHistory();
        record.status_history_id = fieldSetFlags()[0] ? this.status_history_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.driver = fieldSetFlags()[1] ? this.driver : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.insertFrom = fieldSetFlags()[2] ? this.insertFrom : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (locationBuilder != null) {
          try {
            record.location = this.locationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("location"));
            throw e;
          }
        } else {
          record.location = fieldSetFlags()[3] ? this.location : (org.pipeline.trips.avro.DriverLocation) defaultValue(fields()[3]);
        }
        record.status = fieldSetFlags()[4] ? this.status : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.time = fieldSetFlags()[5] ? this.time : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StatusHistory>
    WRITER$ = (org.apache.avro.io.DatumWriter<StatusHistory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StatusHistory>
    READER$ = (org.apache.avro.io.DatumReader<StatusHistory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










