/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StopData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5099990799313189396L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StopData\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"eta\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"distance\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"cost\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"pickup\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"StopLocation\",\"fields\":[{\"name\":\"location\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DriverLocation\",\"fields\":[{\"name\":\"lat\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"lng\",\"type\":[\"null\",\"double\"],\"default\":null}]}],\"default\":null},{\"name\":\"formatted_address\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"destination\",\"type\":[\"null\",\"StopLocation\"],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"stop_data_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StopData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StopData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StopData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StopData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StopData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StopData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StopData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StopData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StopData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer eta;
  private java.lang.Integer distance;
  private java.lang.Integer cost;
  private org.pipeline.trips.avro.StopLocation pickup;
  private org.pipeline.trips.avro.StopLocation destination;
  private java.lang.CharSequence status;
  private java.lang.CharSequence stop_data_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StopData() {}

  /**
   * All-args constructor.
   * @param eta The new value for eta
   * @param distance The new value for distance
   * @param cost The new value for cost
   * @param pickup The new value for pickup
   * @param destination The new value for destination
   * @param status The new value for status
   * @param stop_data_id The new value for stop_data_id
   */
  public StopData(java.lang.Integer eta, java.lang.Integer distance, java.lang.Integer cost, org.pipeline.trips.avro.StopLocation pickup, org.pipeline.trips.avro.StopLocation destination, java.lang.CharSequence status, java.lang.CharSequence stop_data_id) {
    this.eta = eta;
    this.distance = distance;
    this.cost = cost;
    this.pickup = pickup;
    this.destination = destination;
    this.status = status;
    this.stop_data_id = stop_data_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eta;
    case 1: return distance;
    case 2: return cost;
    case 3: return pickup;
    case 4: return destination;
    case 5: return status;
    case 6: return stop_data_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eta = (java.lang.Integer)value$; break;
    case 1: distance = (java.lang.Integer)value$; break;
    case 2: cost = (java.lang.Integer)value$; break;
    case 3: pickup = (org.pipeline.trips.avro.StopLocation)value$; break;
    case 4: destination = (org.pipeline.trips.avro.StopLocation)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    case 6: stop_data_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eta' field.
   * @return The value of the 'eta' field.
   */
  public java.lang.Integer getEta() {
    return eta;
  }


  /**
   * Sets the value of the 'eta' field.
   * @param value the value to set.
   */
  public void setEta(java.lang.Integer value) {
    this.eta = value;
  }

  /**
   * Gets the value of the 'distance' field.
   * @return The value of the 'distance' field.
   */
  public java.lang.Integer getDistance() {
    return distance;
  }


  /**
   * Sets the value of the 'distance' field.
   * @param value the value to set.
   */
  public void setDistance(java.lang.Integer value) {
    this.distance = value;
  }

  /**
   * Gets the value of the 'cost' field.
   * @return The value of the 'cost' field.
   */
  public java.lang.Integer getCost() {
    return cost;
  }


  /**
   * Sets the value of the 'cost' field.
   * @param value the value to set.
   */
  public void setCost(java.lang.Integer value) {
    this.cost = value;
  }

  /**
   * Gets the value of the 'pickup' field.
   * @return The value of the 'pickup' field.
   */
  public org.pipeline.trips.avro.StopLocation getPickup() {
    return pickup;
  }


  /**
   * Sets the value of the 'pickup' field.
   * @param value the value to set.
   */
  public void setPickup(org.pipeline.trips.avro.StopLocation value) {
    this.pickup = value;
  }

  /**
   * Gets the value of the 'destination' field.
   * @return The value of the 'destination' field.
   */
  public org.pipeline.trips.avro.StopLocation getDestination() {
    return destination;
  }


  /**
   * Sets the value of the 'destination' field.
   * @param value the value to set.
   */
  public void setDestination(org.pipeline.trips.avro.StopLocation value) {
    this.destination = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'stop_data_id' field.
   * @return The value of the 'stop_data_id' field.
   */
  public java.lang.CharSequence getStopDataId() {
    return stop_data_id;
  }


  /**
   * Sets the value of the 'stop_data_id' field.
   * @param value the value to set.
   */
  public void setStopDataId(java.lang.CharSequence value) {
    this.stop_data_id = value;
  }

  /**
   * Creates a new StopData RecordBuilder.
   * @return A new StopData RecordBuilder
   */
  public static org.pipeline.trips.avro.StopData.Builder newBuilder() {
    return new org.pipeline.trips.avro.StopData.Builder();
  }

  /**
   * Creates a new StopData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StopData RecordBuilder
   */
  public static org.pipeline.trips.avro.StopData.Builder newBuilder(org.pipeline.trips.avro.StopData.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.StopData.Builder();
    } else {
      return new org.pipeline.trips.avro.StopData.Builder(other);
    }
  }

  /**
   * Creates a new StopData RecordBuilder by copying an existing StopData instance.
   * @param other The existing instance to copy.
   * @return A new StopData RecordBuilder
   */
  public static org.pipeline.trips.avro.StopData.Builder newBuilder(org.pipeline.trips.avro.StopData other) {
    if (other == null) {
      return new org.pipeline.trips.avro.StopData.Builder();
    } else {
      return new org.pipeline.trips.avro.StopData.Builder(other);
    }
  }

  /**
   * RecordBuilder for StopData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StopData>
    implements org.apache.avro.data.RecordBuilder<StopData> {

    private java.lang.Integer eta;
    private java.lang.Integer distance;
    private java.lang.Integer cost;
    private org.pipeline.trips.avro.StopLocation pickup;
    private org.pipeline.trips.avro.StopLocation.Builder pickupBuilder;
    private org.pipeline.trips.avro.StopLocation destination;
    private org.pipeline.trips.avro.StopLocation.Builder destinationBuilder;
    private java.lang.CharSequence status;
    private java.lang.CharSequence stop_data_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.StopData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eta)) {
        this.eta = data().deepCopy(fields()[0].schema(), other.eta);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.distance)) {
        this.distance = data().deepCopy(fields()[1].schema(), other.distance);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cost)) {
        this.cost = data().deepCopy(fields()[2].schema(), other.cost);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.pickup)) {
        this.pickup = data().deepCopy(fields()[3].schema(), other.pickup);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasPickupBuilder()) {
        this.pickupBuilder = org.pipeline.trips.avro.StopLocation.newBuilder(other.getPickupBuilder());
      }
      if (isValidValue(fields()[4], other.destination)) {
        this.destination = data().deepCopy(fields()[4].schema(), other.destination);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasDestinationBuilder()) {
        this.destinationBuilder = org.pipeline.trips.avro.StopLocation.newBuilder(other.getDestinationBuilder());
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.stop_data_id)) {
        this.stop_data_id = data().deepCopy(fields()[6].schema(), other.stop_data_id);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing StopData instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.StopData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eta)) {
        this.eta = data().deepCopy(fields()[0].schema(), other.eta);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.distance)) {
        this.distance = data().deepCopy(fields()[1].schema(), other.distance);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cost)) {
        this.cost = data().deepCopy(fields()[2].schema(), other.cost);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pickup)) {
        this.pickup = data().deepCopy(fields()[3].schema(), other.pickup);
        fieldSetFlags()[3] = true;
      }
      this.pickupBuilder = null;
      if (isValidValue(fields()[4], other.destination)) {
        this.destination = data().deepCopy(fields()[4].schema(), other.destination);
        fieldSetFlags()[4] = true;
      }
      this.destinationBuilder = null;
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.stop_data_id)) {
        this.stop_data_id = data().deepCopy(fields()[6].schema(), other.stop_data_id);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'eta' field.
      * @return The value.
      */
    public java.lang.Integer getEta() {
      return eta;
    }


    /**
      * Sets the value of the 'eta' field.
      * @param value The value of 'eta'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setEta(java.lang.Integer value) {
      validate(fields()[0], value);
      this.eta = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eta' field has been set.
      * @return True if the 'eta' field has been set, false otherwise.
      */
    public boolean hasEta() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eta' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearEta() {
      eta = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'distance' field.
      * @return The value.
      */
    public java.lang.Integer getDistance() {
      return distance;
    }


    /**
      * Sets the value of the 'distance' field.
      * @param value The value of 'distance'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setDistance(java.lang.Integer value) {
      validate(fields()[1], value);
      this.distance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'distance' field has been set.
      * @return True if the 'distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'distance' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearDistance() {
      distance = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cost' field.
      * @return The value.
      */
    public java.lang.Integer getCost() {
      return cost;
    }


    /**
      * Sets the value of the 'cost' field.
      * @param value The value of 'cost'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setCost(java.lang.Integer value) {
      validate(fields()[2], value);
      this.cost = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cost' field has been set.
      * @return True if the 'cost' field has been set, false otherwise.
      */
    public boolean hasCost() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cost' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearCost() {
      cost = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'pickup' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.StopLocation getPickup() {
      return pickup;
    }


    /**
      * Sets the value of the 'pickup' field.
      * @param value The value of 'pickup'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setPickup(org.pipeline.trips.avro.StopLocation value) {
      validate(fields()[3], value);
      this.pickupBuilder = null;
      this.pickup = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'pickup' field has been set.
      * @return True if the 'pickup' field has been set, false otherwise.
      */
    public boolean hasPickup() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'pickup' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.StopLocation.Builder getPickupBuilder() {
      if (pickupBuilder == null) {
        if (hasPickup()) {
          setPickupBuilder(org.pipeline.trips.avro.StopLocation.newBuilder(pickup));
        } else {
          setPickupBuilder(org.pipeline.trips.avro.StopLocation.newBuilder());
        }
      }
      return pickupBuilder;
    }

    /**
     * Sets the Builder instance for the 'pickup' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.StopData.Builder setPickupBuilder(org.pipeline.trips.avro.StopLocation.Builder value) {
      clearPickup();
      pickupBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'pickup' field has an active Builder instance
     * @return True if the 'pickup' field has an active Builder instance
     */
    public boolean hasPickupBuilder() {
      return pickupBuilder != null;
    }

    /**
      * Clears the value of the 'pickup' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearPickup() {
      pickup = null;
      pickupBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'destination' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.StopLocation getDestination() {
      return destination;
    }


    /**
      * Sets the value of the 'destination' field.
      * @param value The value of 'destination'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setDestination(org.pipeline.trips.avro.StopLocation value) {
      validate(fields()[4], value);
      this.destinationBuilder = null;
      this.destination = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'destination' field has been set.
      * @return True if the 'destination' field has been set, false otherwise.
      */
    public boolean hasDestination() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'destination' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.StopLocation.Builder getDestinationBuilder() {
      if (destinationBuilder == null) {
        if (hasDestination()) {
          setDestinationBuilder(org.pipeline.trips.avro.StopLocation.newBuilder(destination));
        } else {
          setDestinationBuilder(org.pipeline.trips.avro.StopLocation.newBuilder());
        }
      }
      return destinationBuilder;
    }

    /**
     * Sets the Builder instance for the 'destination' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.StopData.Builder setDestinationBuilder(org.pipeline.trips.avro.StopLocation.Builder value) {
      clearDestination();
      destinationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'destination' field has an active Builder instance
     * @return True if the 'destination' field has an active Builder instance
     */
    public boolean hasDestinationBuilder() {
      return destinationBuilder != null;
    }

    /**
      * Clears the value of the 'destination' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearDestination() {
      destination = null;
      destinationBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'stop_data_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getStopDataId() {
      return stop_data_id;
    }


    /**
      * Sets the value of the 'stop_data_id' field.
      * @param value The value of 'stop_data_id'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder setStopDataId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.stop_data_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'stop_data_id' field has been set.
      * @return True if the 'stop_data_id' field has been set, false otherwise.
      */
    public boolean hasStopDataId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'stop_data_id' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.StopData.Builder clearStopDataId() {
      stop_data_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StopData build() {
      try {
        StopData record = new StopData();
        record.eta = fieldSetFlags()[0] ? this.eta : (java.lang.Integer) defaultValue(fields()[0]);
        record.distance = fieldSetFlags()[1] ? this.distance : (java.lang.Integer) defaultValue(fields()[1]);
        record.cost = fieldSetFlags()[2] ? this.cost : (java.lang.Integer) defaultValue(fields()[2]);
        if (pickupBuilder != null) {
          try {
            record.pickup = this.pickupBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("pickup"));
            throw e;
          }
        } else {
          record.pickup = fieldSetFlags()[3] ? this.pickup : (org.pipeline.trips.avro.StopLocation) defaultValue(fields()[3]);
        }
        if (destinationBuilder != null) {
          try {
            record.destination = this.destinationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("destination"));
            throw e;
          }
        } else {
          record.destination = fieldSetFlags()[4] ? this.destination : (org.pipeline.trips.avro.StopLocation) defaultValue(fields()[4]);
        }
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.stop_data_id = fieldSetFlags()[6] ? this.stop_data_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StopData>
    WRITER$ = (org.apache.avro.io.DatumWriter<StopData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StopData>
    READER$ = (org.apache.avro.io.DatumReader<StopData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.eta == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.eta);
    }

    if (this.distance == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.distance);
    }

    if (this.cost == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.cost);
    }

    if (this.pickup == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.pickup.customEncode(out);
    }

    if (this.destination == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.destination.customEncode(out);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.stop_data_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.stop_data_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.eta = null;
      } else {
        this.eta = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.distance = null;
      } else {
        this.distance = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.cost = null;
      } else {
        this.cost = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.pickup = null;
      } else {
        if (this.pickup == null) {
          this.pickup = new org.pipeline.trips.avro.StopLocation();
        }
        this.pickup.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.destination = null;
      } else {
        if (this.destination == null) {
          this.destination = new org.pipeline.trips.avro.StopLocation();
        }
        this.destination.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.stop_data_id = null;
      } else {
        this.stop_data_id = in.readString(this.stop_data_id instanceof Utf8 ? (Utf8)this.stop_data_id : null);
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.eta = null;
          } else {
            this.eta = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.distance = null;
          } else {
            this.distance = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.cost = null;
          } else {
            this.cost = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.pickup = null;
          } else {
            if (this.pickup == null) {
              this.pickup = new org.pipeline.trips.avro.StopLocation();
            }
            this.pickup.customDecode(in);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.destination = null;
          } else {
            if (this.destination == null) {
              this.destination = new org.pipeline.trips.avro.StopLocation();
            }
            this.destination.customDecode(in);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.stop_data_id = null;
          } else {
            this.stop_data_id = in.readString(this.stop_data_id instanceof Utf8 ? (Utf8)this.stop_data_id : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










