/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TarifsSimple extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 301741473399797386L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TarifsSimple\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"min_price\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"base_price\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"minute_price\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"km_price\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TarifsSimple> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TarifsSimple> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TarifsSimple> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TarifsSimple> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TarifsSimple> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TarifsSimple to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TarifsSimple from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TarifsSimple instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TarifsSimple fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer min_price;
  private java.lang.Integer base_price;
  private java.lang.Integer minute_price;
  private java.lang.Integer km_price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TarifsSimple() {}

  /**
   * All-args constructor.
   * @param min_price The new value for min_price
   * @param base_price The new value for base_price
   * @param minute_price The new value for minute_price
   * @param km_price The new value for km_price
   */
  public TarifsSimple(java.lang.Integer min_price, java.lang.Integer base_price, java.lang.Integer minute_price, java.lang.Integer km_price) {
    this.min_price = min_price;
    this.base_price = base_price;
    this.minute_price = minute_price;
    this.km_price = km_price;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return min_price;
    case 1: return base_price;
    case 2: return minute_price;
    case 3: return km_price;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: min_price = (java.lang.Integer)value$; break;
    case 1: base_price = (java.lang.Integer)value$; break;
    case 2: minute_price = (java.lang.Integer)value$; break;
    case 3: km_price = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'min_price' field.
   * @return The value of the 'min_price' field.
   */
  public java.lang.Integer getMinPrice() {
    return min_price;
  }


  /**
   * Sets the value of the 'min_price' field.
   * @param value the value to set.
   */
  public void setMinPrice(java.lang.Integer value) {
    this.min_price = value;
  }

  /**
   * Gets the value of the 'base_price' field.
   * @return The value of the 'base_price' field.
   */
  public java.lang.Integer getBasePrice() {
    return base_price;
  }


  /**
   * Sets the value of the 'base_price' field.
   * @param value the value to set.
   */
  public void setBasePrice(java.lang.Integer value) {
    this.base_price = value;
  }

  /**
   * Gets the value of the 'minute_price' field.
   * @return The value of the 'minute_price' field.
   */
  public java.lang.Integer getMinutePrice() {
    return minute_price;
  }


  /**
   * Sets the value of the 'minute_price' field.
   * @param value the value to set.
   */
  public void setMinutePrice(java.lang.Integer value) {
    this.minute_price = value;
  }

  /**
   * Gets the value of the 'km_price' field.
   * @return The value of the 'km_price' field.
   */
  public java.lang.Integer getKmPrice() {
    return km_price;
  }


  /**
   * Sets the value of the 'km_price' field.
   * @param value the value to set.
   */
  public void setKmPrice(java.lang.Integer value) {
    this.km_price = value;
  }

  /**
   * Creates a new TarifsSimple RecordBuilder.
   * @return A new TarifsSimple RecordBuilder
   */
  public static org.pipeline.trips.avro.TarifsSimple.Builder newBuilder() {
    return new org.pipeline.trips.avro.TarifsSimple.Builder();
  }

  /**
   * Creates a new TarifsSimple RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TarifsSimple RecordBuilder
   */
  public static org.pipeline.trips.avro.TarifsSimple.Builder newBuilder(org.pipeline.trips.avro.TarifsSimple.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TarifsSimple.Builder();
    } else {
      return new org.pipeline.trips.avro.TarifsSimple.Builder(other);
    }
  }

  /**
   * Creates a new TarifsSimple RecordBuilder by copying an existing TarifsSimple instance.
   * @param other The existing instance to copy.
   * @return A new TarifsSimple RecordBuilder
   */
  public static org.pipeline.trips.avro.TarifsSimple.Builder newBuilder(org.pipeline.trips.avro.TarifsSimple other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TarifsSimple.Builder();
    } else {
      return new org.pipeline.trips.avro.TarifsSimple.Builder(other);
    }
  }

  /**
   * RecordBuilder for TarifsSimple instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TarifsSimple>
    implements org.apache.avro.data.RecordBuilder<TarifsSimple> {

    private java.lang.Integer min_price;
    private java.lang.Integer base_price;
    private java.lang.Integer minute_price;
    private java.lang.Integer km_price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.TarifsSimple.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.min_price)) {
        this.min_price = data().deepCopy(fields()[0].schema(), other.min_price);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.base_price)) {
        this.base_price = data().deepCopy(fields()[1].schema(), other.base_price);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.minute_price)) {
        this.minute_price = data().deepCopy(fields()[2].schema(), other.minute_price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.km_price)) {
        this.km_price = data().deepCopy(fields()[3].schema(), other.km_price);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TarifsSimple instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.TarifsSimple other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.min_price)) {
        this.min_price = data().deepCopy(fields()[0].schema(), other.min_price);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.base_price)) {
        this.base_price = data().deepCopy(fields()[1].schema(), other.base_price);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.minute_price)) {
        this.minute_price = data().deepCopy(fields()[2].schema(), other.minute_price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.km_price)) {
        this.km_price = data().deepCopy(fields()[3].schema(), other.km_price);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'min_price' field.
      * @return The value.
      */
    public java.lang.Integer getMinPrice() {
      return min_price;
    }


    /**
      * Sets the value of the 'min_price' field.
      * @param value The value of 'min_price'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder setMinPrice(java.lang.Integer value) {
      validate(fields()[0], value);
      this.min_price = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'min_price' field has been set.
      * @return True if the 'min_price' field has been set, false otherwise.
      */
    public boolean hasMinPrice() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'min_price' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder clearMinPrice() {
      min_price = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'base_price' field.
      * @return The value.
      */
    public java.lang.Integer getBasePrice() {
      return base_price;
    }


    /**
      * Sets the value of the 'base_price' field.
      * @param value The value of 'base_price'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder setBasePrice(java.lang.Integer value) {
      validate(fields()[1], value);
      this.base_price = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'base_price' field has been set.
      * @return True if the 'base_price' field has been set, false otherwise.
      */
    public boolean hasBasePrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'base_price' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder clearBasePrice() {
      base_price = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'minute_price' field.
      * @return The value.
      */
    public java.lang.Integer getMinutePrice() {
      return minute_price;
    }


    /**
      * Sets the value of the 'minute_price' field.
      * @param value The value of 'minute_price'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder setMinutePrice(java.lang.Integer value) {
      validate(fields()[2], value);
      this.minute_price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'minute_price' field has been set.
      * @return True if the 'minute_price' field has been set, false otherwise.
      */
    public boolean hasMinutePrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'minute_price' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder clearMinutePrice() {
      minute_price = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'km_price' field.
      * @return The value.
      */
    public java.lang.Integer getKmPrice() {
      return km_price;
    }


    /**
      * Sets the value of the 'km_price' field.
      * @param value The value of 'km_price'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder setKmPrice(java.lang.Integer value) {
      validate(fields()[3], value);
      this.km_price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'km_price' field has been set.
      * @return True if the 'km_price' field has been set, false otherwise.
      */
    public boolean hasKmPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'km_price' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TarifsSimple.Builder clearKmPrice() {
      km_price = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TarifsSimple build() {
      try {
        TarifsSimple record = new TarifsSimple();
        record.min_price = fieldSetFlags()[0] ? this.min_price : (java.lang.Integer) defaultValue(fields()[0]);
        record.base_price = fieldSetFlags()[1] ? this.base_price : (java.lang.Integer) defaultValue(fields()[1]);
        record.minute_price = fieldSetFlags()[2] ? this.minute_price : (java.lang.Integer) defaultValue(fields()[2]);
        record.km_price = fieldSetFlags()[3] ? this.km_price : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TarifsSimple>
    WRITER$ = (org.apache.avro.io.DatumWriter<TarifsSimple>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TarifsSimple>
    READER$ = (org.apache.avro.io.DatumReader<TarifsSimple>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.min_price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.min_price);
    }

    if (this.base_price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.base_price);
    }

    if (this.minute_price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.minute_price);
    }

    if (this.km_price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.km_price);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.min_price = null;
      } else {
        this.min_price = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.base_price = null;
      } else {
        this.base_price = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.minute_price = null;
      } else {
        this.minute_price = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.km_price = null;
      } else {
        this.km_price = in.readInt();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.min_price = null;
          } else {
            this.min_price = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.base_price = null;
          } else {
            this.base_price = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.minute_price = null;
          } else {
            this.minute_price = in.readInt();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.km_price = null;
          } else {
            this.km_price = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










