/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TipEpayStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2565223169954934834L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TipEpayStatus\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"current\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"code\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"note\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"updated_at\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TipEpayStatus> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TipEpayStatus> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TipEpayStatus> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TipEpayStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TipEpayStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TipEpayStatus to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TipEpayStatus from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TipEpayStatus instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TipEpayStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence current;
  private java.lang.Integer code;
  private java.lang.CharSequence note;
  private java.lang.CharSequence created_at;
  private java.lang.CharSequence updated_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TipEpayStatus() {}

  /**
   * All-args constructor.
   * @param current The new value for current
   * @param code The new value for code
   * @param note The new value for note
   * @param created_at The new value for created_at
   * @param updated_at The new value for updated_at
   */
  public TipEpayStatus(java.lang.CharSequence current, java.lang.Integer code, java.lang.CharSequence note, java.lang.CharSequence created_at, java.lang.CharSequence updated_at) {
    this.current = current;
    this.code = code;
    this.note = note;
    this.created_at = created_at;
    this.updated_at = updated_at;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return current;
    case 1: return code;
    case 2: return note;
    case 3: return created_at;
    case 4: return updated_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: current = (java.lang.CharSequence)value$; break;
    case 1: code = (java.lang.Integer)value$; break;
    case 2: note = (java.lang.CharSequence)value$; break;
    case 3: created_at = (java.lang.CharSequence)value$; break;
    case 4: updated_at = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'current' field.
   * @return The value of the 'current' field.
   */
  public java.lang.CharSequence getCurrent() {
    return current;
  }


  /**
   * Sets the value of the 'current' field.
   * @param value the value to set.
   */
  public void setCurrent(java.lang.CharSequence value) {
    this.current = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.Integer getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.Integer value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'note' field.
   * @return The value of the 'note' field.
   */
  public java.lang.CharSequence getNote() {
    return note;
  }


  /**
   * Sets the value of the 'note' field.
   * @param value the value to set.
   */
  public void setNote(java.lang.CharSequence value) {
    this.note = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   * @return The value of the 'updated_at' field.
   */
  public java.lang.CharSequence getUpdatedAt() {
    return updated_at;
  }


  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.CharSequence value) {
    this.updated_at = value;
  }

  /**
   * Creates a new TipEpayStatus RecordBuilder.
   * @return A new TipEpayStatus RecordBuilder
   */
  public static org.pipeline.trips.avro.TipEpayStatus.Builder newBuilder() {
    return new org.pipeline.trips.avro.TipEpayStatus.Builder();
  }

  /**
   * Creates a new TipEpayStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TipEpayStatus RecordBuilder
   */
  public static org.pipeline.trips.avro.TipEpayStatus.Builder newBuilder(org.pipeline.trips.avro.TipEpayStatus.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TipEpayStatus.Builder();
    } else {
      return new org.pipeline.trips.avro.TipEpayStatus.Builder(other);
    }
  }

  /**
   * Creates a new TipEpayStatus RecordBuilder by copying an existing TipEpayStatus instance.
   * @param other The existing instance to copy.
   * @return A new TipEpayStatus RecordBuilder
   */
  public static org.pipeline.trips.avro.TipEpayStatus.Builder newBuilder(org.pipeline.trips.avro.TipEpayStatus other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TipEpayStatus.Builder();
    } else {
      return new org.pipeline.trips.avro.TipEpayStatus.Builder(other);
    }
  }

  /**
   * RecordBuilder for TipEpayStatus instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TipEpayStatus>
    implements org.apache.avro.data.RecordBuilder<TipEpayStatus> {

    private java.lang.CharSequence current;
    private java.lang.Integer code;
    private java.lang.CharSequence note;
    private java.lang.CharSequence created_at;
    private java.lang.CharSequence updated_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.TipEpayStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.current)) {
        this.current = data().deepCopy(fields()[0].schema(), other.current);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.note)) {
        this.note = data().deepCopy(fields()[2].schema(), other.note);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[4].schema(), other.updated_at);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing TipEpayStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.TipEpayStatus other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.current)) {
        this.current = data().deepCopy(fields()[0].schema(), other.current);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.note)) {
        this.note = data().deepCopy(fields()[2].schema(), other.note);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[4].schema(), other.updated_at);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'current' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrent() {
      return current;
    }


    /**
      * Sets the value of the 'current' field.
      * @param value The value of 'current'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder setCurrent(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.current = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'current' field has been set.
      * @return True if the 'current' field has been set, false otherwise.
      */
    public boolean hasCurrent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'current' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder clearCurrent() {
      current = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.Integer getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder setCode(java.lang.Integer value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'note' field.
      * @return The value.
      */
    public java.lang.CharSequence getNote() {
      return note;
    }


    /**
      * Sets the value of the 'note' field.
      * @param value The value of 'note'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder setNote(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.note = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'note' field has been set.
      * @return True if the 'note' field has been set, false otherwise.
      */
    public boolean hasNote() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'note' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder clearNote() {
      note = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.created_at = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_at' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedAt() {
      return updated_at;
    }


    /**
      * Sets the value of the 'updated_at' field.
      * @param value The value of 'updated_at'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder setUpdatedAt(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.updated_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_at' field has been set.
      * @return True if the 'updated_at' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'updated_at' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TipEpayStatus.Builder clearUpdatedAt() {
      updated_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TipEpayStatus build() {
      try {
        TipEpayStatus record = new TipEpayStatus();
        record.current = fieldSetFlags()[0] ? this.current : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.Integer) defaultValue(fields()[1]);
        record.note = fieldSetFlags()[2] ? this.note : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.created_at = fieldSetFlags()[3] ? this.created_at : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.updated_at = fieldSetFlags()[4] ? this.updated_at : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TipEpayStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<TipEpayStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TipEpayStatus>
    READER$ = (org.apache.avro.io.DatumReader<TipEpayStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.current == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.current);
    }

    if (this.code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.code);
    }

    if (this.note == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.note);
    }

    if (this.created_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.created_at);
    }

    if (this.updated_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.updated_at);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.current = null;
      } else {
        this.current = in.readString(this.current instanceof Utf8 ? (Utf8)this.current : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.code = null;
      } else {
        this.code = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.note = null;
      } else {
        this.note = in.readString(this.note instanceof Utf8 ? (Utf8)this.note : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.created_at = null;
      } else {
        this.created_at = in.readString(this.created_at instanceof Utf8 ? (Utf8)this.created_at : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.updated_at = null;
      } else {
        this.updated_at = in.readString(this.updated_at instanceof Utf8 ? (Utf8)this.updated_at : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.current = null;
          } else {
            this.current = in.readString(this.current instanceof Utf8 ? (Utf8)this.current : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.code = null;
          } else {
            this.code = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.note = null;
          } else {
            this.note = in.readString(this.note instanceof Utf8 ? (Utf8)this.note : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.created_at = null;
          } else {
            this.created_at = in.readString(this.created_at instanceof Utf8 ? (Utf8)this.created_at : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.updated_at = null;
          } else {
            this.updated_at = in.readString(this.updated_at instanceof Utf8 ? (Utf8)this.updated_at : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










