/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.pipeline.trips.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TripDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 256598355766437701L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TripDetails\",\"namespace\":\"org.pipeline.trips.avro\",\"fields\":[{\"name\":\"service\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Service\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"label\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Label\",\"fields\":[{\"name\":\"ar\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"en\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fr\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}],\"default\":null},{\"name\":\"servicetype\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ServiceType\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"label\",\"type\":[\"null\",\"Label\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TripDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TripDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TripDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TripDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TripDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TripDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TripDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TripDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TripDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private org.pipeline.trips.avro.Service service;
  private org.pipeline.trips.avro.ServiceType servicetype;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TripDetails() {}

  /**
   * All-args constructor.
   * @param service The new value for service
   * @param servicetype The new value for servicetype
   */
  public TripDetails(org.pipeline.trips.avro.Service service, org.pipeline.trips.avro.ServiceType servicetype) {
    this.service = service;
    this.servicetype = servicetype;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return service;
    case 1: return servicetype;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: service = (org.pipeline.trips.avro.Service)value$; break;
    case 1: servicetype = (org.pipeline.trips.avro.ServiceType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'service' field.
   * @return The value of the 'service' field.
   */
  public org.pipeline.trips.avro.Service getService() {
    return service;
  }


  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(org.pipeline.trips.avro.Service value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'servicetype' field.
   * @return The value of the 'servicetype' field.
   */
  public org.pipeline.trips.avro.ServiceType getServicetype() {
    return servicetype;
  }


  /**
   * Sets the value of the 'servicetype' field.
   * @param value the value to set.
   */
  public void setServicetype(org.pipeline.trips.avro.ServiceType value) {
    this.servicetype = value;
  }

  /**
   * Creates a new TripDetails RecordBuilder.
   * @return A new TripDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.TripDetails.Builder newBuilder() {
    return new org.pipeline.trips.avro.TripDetails.Builder();
  }

  /**
   * Creates a new TripDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TripDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.TripDetails.Builder newBuilder(org.pipeline.trips.avro.TripDetails.Builder other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TripDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.TripDetails.Builder(other);
    }
  }

  /**
   * Creates a new TripDetails RecordBuilder by copying an existing TripDetails instance.
   * @param other The existing instance to copy.
   * @return A new TripDetails RecordBuilder
   */
  public static org.pipeline.trips.avro.TripDetails.Builder newBuilder(org.pipeline.trips.avro.TripDetails other) {
    if (other == null) {
      return new org.pipeline.trips.avro.TripDetails.Builder();
    } else {
      return new org.pipeline.trips.avro.TripDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for TripDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TripDetails>
    implements org.apache.avro.data.RecordBuilder<TripDetails> {

    private org.pipeline.trips.avro.Service service;
    private org.pipeline.trips.avro.Service.Builder serviceBuilder;
    private org.pipeline.trips.avro.ServiceType servicetype;
    private org.pipeline.trips.avro.ServiceType.Builder servicetypeBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.pipeline.trips.avro.TripDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.service)) {
        this.service = data().deepCopy(fields()[0].schema(), other.service);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasServiceBuilder()) {
        this.serviceBuilder = org.pipeline.trips.avro.Service.newBuilder(other.getServiceBuilder());
      }
      if (isValidValue(fields()[1], other.servicetype)) {
        this.servicetype = data().deepCopy(fields()[1].schema(), other.servicetype);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasServicetypeBuilder()) {
        this.servicetypeBuilder = org.pipeline.trips.avro.ServiceType.newBuilder(other.getServicetypeBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TripDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(org.pipeline.trips.avro.TripDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.service)) {
        this.service = data().deepCopy(fields()[0].schema(), other.service);
        fieldSetFlags()[0] = true;
      }
      this.serviceBuilder = null;
      if (isValidValue(fields()[1], other.servicetype)) {
        this.servicetype = data().deepCopy(fields()[1].schema(), other.servicetype);
        fieldSetFlags()[1] = true;
      }
      this.servicetypeBuilder = null;
    }

    /**
      * Gets the value of the 'service' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.Service getService() {
      return service;
    }


    /**
      * Sets the value of the 'service' field.
      * @param value The value of 'service'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TripDetails.Builder setService(org.pipeline.trips.avro.Service value) {
      validate(fields()[0], value);
      this.serviceBuilder = null;
      this.service = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'service' field has been set.
      * @return True if the 'service' field has been set, false otherwise.
      */
    public boolean hasService() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'service' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.Service.Builder getServiceBuilder() {
      if (serviceBuilder == null) {
        if (hasService()) {
          setServiceBuilder(org.pipeline.trips.avro.Service.newBuilder(service));
        } else {
          setServiceBuilder(org.pipeline.trips.avro.Service.newBuilder());
        }
      }
      return serviceBuilder;
    }

    /**
     * Sets the Builder instance for the 'service' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.TripDetails.Builder setServiceBuilder(org.pipeline.trips.avro.Service.Builder value) {
      clearService();
      serviceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'service' field has an active Builder instance
     * @return True if the 'service' field has an active Builder instance
     */
    public boolean hasServiceBuilder() {
      return serviceBuilder != null;
    }

    /**
      * Clears the value of the 'service' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TripDetails.Builder clearService() {
      service = null;
      serviceBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'servicetype' field.
      * @return The value.
      */
    public org.pipeline.trips.avro.ServiceType getServicetype() {
      return servicetype;
    }


    /**
      * Sets the value of the 'servicetype' field.
      * @param value The value of 'servicetype'.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TripDetails.Builder setServicetype(org.pipeline.trips.avro.ServiceType value) {
      validate(fields()[1], value);
      this.servicetypeBuilder = null;
      this.servicetype = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'servicetype' field has been set.
      * @return True if the 'servicetype' field has been set, false otherwise.
      */
    public boolean hasServicetype() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'servicetype' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.pipeline.trips.avro.ServiceType.Builder getServicetypeBuilder() {
      if (servicetypeBuilder == null) {
        if (hasServicetype()) {
          setServicetypeBuilder(org.pipeline.trips.avro.ServiceType.newBuilder(servicetype));
        } else {
          setServicetypeBuilder(org.pipeline.trips.avro.ServiceType.newBuilder());
        }
      }
      return servicetypeBuilder;
    }

    /**
     * Sets the Builder instance for the 'servicetype' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.pipeline.trips.avro.TripDetails.Builder setServicetypeBuilder(org.pipeline.trips.avro.ServiceType.Builder value) {
      clearServicetype();
      servicetypeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'servicetype' field has an active Builder instance
     * @return True if the 'servicetype' field has an active Builder instance
     */
    public boolean hasServicetypeBuilder() {
      return servicetypeBuilder != null;
    }

    /**
      * Clears the value of the 'servicetype' field.
      * @return This builder.
      */
    public org.pipeline.trips.avro.TripDetails.Builder clearServicetype() {
      servicetype = null;
      servicetypeBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TripDetails build() {
      try {
        TripDetails record = new TripDetails();
        if (serviceBuilder != null) {
          try {
            record.service = this.serviceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("service"));
            throw e;
          }
        } else {
          record.service = fieldSetFlags()[0] ? this.service : (org.pipeline.trips.avro.Service) defaultValue(fields()[0]);
        }
        if (servicetypeBuilder != null) {
          try {
            record.servicetype = this.servicetypeBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("servicetype"));
            throw e;
          }
        } else {
          record.servicetype = fieldSetFlags()[1] ? this.servicetype : (org.pipeline.trips.avro.ServiceType) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TripDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<TripDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TripDetails>
    READER$ = (org.apache.avro.io.DatumReader<TripDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.service == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.service.customEncode(out);
    }

    if (this.servicetype == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.servicetype.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.service = null;
      } else {
        if (this.service == null) {
          this.service = new org.pipeline.trips.avro.Service();
        }
        this.service.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.servicetype = null;
      } else {
        if (this.servicetype == null) {
          this.servicetype = new org.pipeline.trips.avro.ServiceType();
        }
        this.servicetype.customDecode(in);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.service = null;
          } else {
            if (this.service == null) {
              this.service = new org.pipeline.trips.avro.Service();
            }
            this.service.customDecode(in);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.servicetype = null;
          } else {
            if (this.servicetype == null) {
              this.servicetype = new org.pipeline.trips.avro.ServiceType();
            }
            this.servicetype.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










